// Auto-generated by scripts/build-engine-browser.mjs

"use strict";
(() => {
  var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
    get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
  }) : x)(function(x) {
    if (typeof require !== "undefined") return require.apply(this, arguments);
    throw Error('Dynamic require of "' + x + '" is not supported');
  });

  // engine-src/packages/analyzers/src/cfg.ts
  var idc = 0;
  function nid(prefix) {
    idc += 1;
    return `${prefix}_${idc}`;
  }
  function buildCFG(fn) {
    idc = 0;
    const nodes = [];
    const edges = [];
    const start = nid("start");
    const end = nid("end");
    nodes.push({ id: start, kind: "start", label: "Start" });
    nodes.push({ id: end, kind: "end", label: "End" });
    function seq(stmts) {
      if (!stmts || stmts.length === 0) {
        const x = nid("op");
        nodes.push({ id: x, kind: "op", label: "pass" });
        return { entry: x, exits: [x] };
      }
      let first = null;
      let prevExits = [];
      for (const s of stmts) {
        const { entry, exits } = build(s);
        if (!first) first = entry;
        for (const p of prevExits) edges.push({ from: p, to: entry });
        prevExits = exits;
      }
      return { entry: first, exits: prevExits };
    }
    function build(s) {
      switch (s.kind) {
        case "if": {
          const d = nid("dec");
          nodes.push({ id: d, kind: "decision", label: `if ${s.cond}?` });
          const t = seq(s.then || []);
          edges.push({ from: d, to: t.entry, label: "True" });
          const e = s.else ? seq(s.else) : { entry: d, exits: [d] };
          if (s.else) edges.push({ from: d, to: e.entry, label: "False" });
          const m = nid("merge");
          nodes.push({ id: m, kind: "merge", label: "merge" });
          for (const x of t.exits) edges.push({ from: x, to: m });
          for (const x of e.exits) edges.push({ from: x, to: m });
          return { entry: d, exits: [m] };
        }
        case "for": {
          const d = nid("loop");
          nodes.push({ id: d, kind: "loop", label: `for ${s.target} in ${s.iter}` });
          const b = seq(s.body || []);
          edges.push({ from: d, to: b.entry, label: "loop" });
          for (const x of b.exits) edges.push({ from: x, to: d, label: "next" });
          const m = nid("merge");
          nodes.push({ id: m, kind: "merge", label: "exit" });
          edges.push({ from: d, to: m, label: "exit" });
          return { entry: d, exits: [m] };
        }
        case "while": {
          const d = nid("dec");
          nodes.push({ id: d, kind: "decision", label: `while ${s.cond}?` });
          const b = seq(s.body || []);
          edges.push({ from: d, to: b.entry, label: "True" });
          for (const x of b.exits) edges.push({ from: x, to: d, label: "loop" });
          const m = nid("merge");
          nodes.push({ id: m, kind: "merge", label: "False" });
          edges.push({ from: d, to: m, label: "False" });
          return { entry: d, exits: [m] };
        }
        case "try": {
          const t = seq(s.body || []);
          const d = nid("try");
          nodes.push({ id: d, kind: "try", label: "try" });
          edges.push({ from: d, to: t.entry });
          const merges = [];
          for (const h of s.excepts || []) {
            const hb = seq(h.body || []);
            const ex = nid("ex");
            nodes.push({ id: ex, kind: "except", label: `except ${h.type || ""}` });
            edges.push({ from: d, to: hb.entry });
            merges.push(...hb.exits);
          }
          const m = nid("merge");
          nodes.push({ id: m, kind: "merge", label: "merge" });
          for (const x of t.exits.concat(merges)) edges.push({ from: x, to: m });
          return { entry: d, exits: [m] };
        }
        default: {
          const n = nid("op");
          nodes.push({ id: n, kind: "op", label: s.text || s.kind });
          if (s.kind === "return" || s.kind === "raise") {
            edges.push({ from: n, to: end });
            return { entry: n, exits: [end] };
          }
          return { entry: n, exits: [n] };
        }
      }
    }
    if (!fn.body || fn.body.length === 0) {
      edges.push({ from: start, to: end });
    } else {
      const { entry, exits } = seq(fn.body);
      edges.push({ from: start, to: entry });
      for (const x of exits) edges.push({ from: x, to: end });
    }
    return { nodes, edges };
  }

  // engine-src/packages/analyzers/src/calls.ts
  function buildCallGraph(project) {
    const edges = [];
    const nameToId = /* @__PURE__ */ new Map();
    const register2 = (name, id) => {
      if (!name) return;
      const normalized = name.replace(/::/g, ".");
      if (!nameToId.has(normalized)) {
        nameToId.set(normalized, id);
      }
    };
    for (const mod of Object.values(project.modules)) {
      for (const fn of mod.functions) {
        register2(fn.id, fn.id);
        register2(`${mod.name}.${fn.name}`, fn.id);
        register2(fn.name, fn.id);
      }
      for (const cls of mod.classes || []) {
        for (const method of cls.methods || []) {
          register2(method.id, method.id);
          register2(`${mod.name}.${method.name}`, method.id);
          register2(`${cls.name}.${method.name}`, method.id);
          register2(`${mod.name}.${cls.name}.${method.name}`, method.id);
          register2(method.name, method.id);
        }
      }
    }
    const resolveTarget = (rawName) => {
      if (!rawName) return void 0;
      const normalized = rawName.replace(/::/g, ".");
      const direct = nameToId.get(normalized);
      if (direct) return direct;
      const parts = normalized.split(".");
      for (let i = 0; i < parts.length; i += 1) {
        const suffix = parts.slice(i).join(".");
        const match = nameToId.get(suffix);
        if (match) return match;
      }
      return void 0;
    };
    for (const mod of Object.values(project.modules)) {
      for (const fn of mod.functions) {
        for (const callee of fn.calls || []) {
          const toId = resolveTarget(callee);
          edges.push({ from: fn.id, toName: callee, toId });
        }
      }
      for (const cls of mod.classes || []) {
        for (const method of cls.methods || []) {
          for (const callee of method.calls || []) {
            const toId = resolveTarget(callee);
            edges.push({ from: method.id, toName: callee, toId });
          }
        }
      }
    }
    return { edges };
  }

  // scripts/lib/path-browser-shim.js
  function extname(input = "") {
    const normalized = String(input);
    const lastDot = normalized.lastIndexOf(".");
    const lastSlash = Math.max(normalized.lastIndexOf("/"), normalized.lastIndexOf("\\"));
    if (lastDot <= lastSlash) return "";
    return normalized.slice(lastDot);
  }
  function join(...segments) {
    const parts = segments.flatMap((segment) => String(segment || "").split(/[\\/]+/)).filter(Boolean);
    let joined = parts.join("/");
    if (segments.length && String(segments[0] || "").startsWith("/")) {
      joined = `/${joined}`;
    }
    return joined || ".";
  }
  var path_browser_shim_default = { extname, join };

  // engine-src/packages/analyzers/src/dependencies.ts
  function normalizePath(filePath) {
    return filePath.replace(/\\/g, "/");
  }
  function stripExtension(filePath) {
    if (filePath.endsWith(".d.ts")) {
      return filePath.slice(0, -5);
    }
    return filePath.replace(/\.[^.\/]+$/g, "");
  }
  function inferLanguage(mod) {
    const lower = mod.path?.toLowerCase() ?? "";
    if (lower.endsWith(".py") || lower.endsWith(".pyw") || lower.endsWith(".pyi")) {
      return "python";
    }
    if (lower.endsWith(".ts") || lower.endsWith(".tsx")) {
      return "typescript";
    }
    if (lower.endsWith(".js") || lower.endsWith(".jsx") || lower.endsWith(".mjs") || lower.endsWith(".cjs")) {
      return "javascript";
    }
    return "unknown";
  }
  function resolvePythonModuleName(mod, spec) {
    const trimmed = spec.trim();
    if (!trimmed) return mod.name;
    if (!trimmed.startsWith(".")) return trimmed;
    const moduleParts = mod.name.split(".");
    const packageParts = moduleParts.slice(0, -1);
    let dotCount = 0;
    while (dotCount < trimmed.length && trimmed[dotCount] === ".") {
      dotCount += 1;
    }
    let levelsUp = Math.max(0, dotCount - 1);
    const remainder = trimmed.slice(dotCount);
    const baseParts = packageParts.slice();
    while (levelsUp > 0 && baseParts.length > 0) {
      baseParts.pop();
      levelsUp -= 1;
    }
    const remainderParts = remainder ? remainder.split(".").map((part) => part.trim()).filter(Boolean) : [];
    const resolved = baseParts.concat(remainderParts);
    if (resolved.length === 0) {
      return moduleParts.join(".");
    }
    return resolved.join(".");
  }
  function extractPythonSymbols(segment) {
    return segment.replace(/[()]/g, " ").split(",").map((part) => part.trim()).map((part) => part.replace(/\s+as\s+[A-Za-z0-9_]+$/i, "").trim()).filter(Boolean);
  }
  function parsePythonImport(mod, raw) {
    const normalized = raw.replace(/\s+/g, " ").trim();
    if (!normalized) return [];
    const results = [];
    const colonIdx = normalized.indexOf(":");
    if (colonIdx > 0) {
      const moduleChunk = normalized.slice(0, colonIdx);
      if (/^[A-Za-z0-9_.]+$/.test(moduleChunk)) {
        const moduleName = resolvePythonModuleName(mod, moduleChunk);
        const symbols = extractPythonSymbols(normalized.slice(colonIdx + 1));
        results.push({ module: moduleName, symbols: symbols.length ? symbols : void 0 });
        return results;
      }
    }
    const fromMatch = /^from\s+([A-Za-z0-9_.]+|\.+)\s+import\s+([\s\S]+)$/i.exec(normalized);
    if (fromMatch) {
      const moduleName = resolvePythonModuleName(mod, fromMatch[1]);
      const symbols = extractPythonSymbols(fromMatch[2]);
      results.push({ module: moduleName, symbols: symbols.length ? symbols : void 0 });
      return results;
    }
    const importMatch = /^import\s+([\s\S]+)$/i.exec(normalized);
    if (importMatch) {
      const parts = importMatch[1].split(",").map((part) => part.trim()).filter(Boolean);
      for (const part of parts) {
        const cleaned = part.replace(/\s+as\s+[A-Za-z0-9_]+$/i, "").trim();
        if (!cleaned) continue;
        const moduleName = resolvePythonModuleName(mod, cleaned);
        results.push({ module: moduleName });
      }
      return results;
    }
    if (/^[A-Za-z0-9_.]+$/.test(normalized) || normalized.startsWith(".")) {
      const moduleName = resolvePythonModuleName(mod, normalized);
      results.push({ module: moduleName });
      return results;
    }
    return results;
  }
  function mergeSymbols(existing, next) {
    if ((!existing || existing.length === 0) && (!next || next.length === 0)) {
      return void 0;
    }
    const set = /* @__PURE__ */ new Set();
    for (const symbol of existing || []) {
      if (symbol) set.add(symbol);
    }
    for (const symbol of next || []) {
      if (symbol) set.add(symbol);
    }
    return Array.from(set).sort((a, b) => a.localeCompare(b));
  }
  function extractJSImportSymbols(clause) {
    if (!clause) return [];
    const text = clause.trim();
    if (!text) return [];
    const names = /* @__PURE__ */ new Set();
    const curlyMatch = text.match(/\{([^}]*)\}/);
    if (curlyMatch) {
      const inner = curlyMatch[1];
      inner.split(",").map((part) => part.trim()).forEach((part) => {
        if (!part) return;
        const cleaned = part.replace(/\s+as\s+[A-Za-z0-9_$]+$/i, "").trim();
        if (cleaned) names.add(cleaned);
      });
    }
    if (/^\*\s+as\s+/i.test(text)) {
      names.add("*");
    }
    return Array.from(names).sort((a, b) => a.localeCompare(b));
  }
  function parseJSImport(raw) {
    const trimmed = raw.trim();
    if (!trimmed) return [];
    const entries = /* @__PURE__ */ new Map();
    const add = (module, symbols) => {
      const existing = entries.get(module);
      if (existing) {
        existing.symbols = mergeSymbols(existing.symbols, symbols);
      } else {
        entries.set(module, {
          module,
          symbols: symbols && symbols.length ? mergeSymbols([], symbols) : void 0
        });
      }
    };
    const importFromRegex = /import\s+(?:type\s+)?([\s\S]+?)\s+from\s+['"]([^'"\\]+)['"]/gi;
    let match;
    while (match = importFromRegex.exec(trimmed)) {
      const clause = match[1];
      const spec = match[2];
      const symbols = extractJSImportSymbols(clause);
      add(spec, symbols);
    }
    const exportFromRegex = /export\s+(?:type\s+)?(?:\{([^}]*)\}|\*)\s+from\s+['"]([^'"\\]+)['"]/gi;
    while (match = exportFromRegex.exec(trimmed)) {
      const namesBlock = match[1];
      const spec = match[2];
      const isStar = match[0].includes("*");
      const symbols = namesBlock ? extractJSImportSymbols(`{${namesBlock}}`) : isStar ? ["*"] : void 0;
      add(spec, symbols);
    }
    const requireRegex = /require\((['"])([^'"\\]+)\1\)/g;
    while (match = requireRegex.exec(trimmed)) {
      add(match[2]);
    }
    const dynamicImportRegex = /import\((['"])([^'"\\]+)\1\)/g;
    while (match = dynamicImportRegex.exec(trimmed)) {
      add(match[2]);
    }
    const bareImportRegex = /import\s+['"]([^'"\\]+)['"]/gi;
    while (match = bareImportRegex.exec(trimmed)) {
      add(match[1]);
    }
    if (entries.size === 0 && /^[A-Za-z0-9@._\/-]+$/.test(trimmed)) {
      add(trimmed);
    }
    return Array.from(entries.values());
  }
  function resolveJSImportTarget(mod, spec, pathToModule, moduleNames) {
    const trimmed = spec.trim();
    if (!trimmed) {
      return { target: spec, isExternal: true };
    }
    const normalized = trimmed.replace(/\\/g, "/");
    const withoutExt = stripExtension(normalized);
    const directCandidates = /* @__PURE__ */ new Set([
      trimmed,
      normalized,
      withoutExt,
      withoutExt.replace(/\/index$/i, "")
    ]);
    for (const candidate of directCandidates) {
      if (moduleNames.has(candidate)) {
        return { target: candidate, isExternal: false };
      }
      const dotted = candidate.replace(/\//g, ".");
      if (moduleNames.has(dotted)) {
        return { target: dotted, isExternal: false };
      }
    }
    if (normalized.startsWith(".")) {
      const fromPath = normalizePath(mod.path);
      const baseDir = path_browser_shim_default.posix.dirname(fromPath);
      const joined = path_browser_shim_default.posix.normalize(path_browser_shim_default.posix.join(baseDir, normalized));
      const joinedNoExt = stripExtension(joined);
      const match = pathToModule.get(joinedNoExt) ?? pathToModule.get(`${joinedNoExt}/index`);
      if (match) {
        return { target: match, isExternal: false };
      }
      const dotted = joinedNoExt.replace(/\//g, ".");
      if (moduleNames.has(dotted)) {
        return { target: dotted, isExternal: false };
      }
    } else if (normalized.startsWith("/")) {
      const absolute = stripExtension(path_browser_shim_default.posix.normalize(normalized));
      const match = pathToModule.get(absolute) ?? pathToModule.get(`${absolute}/index`);
      if (match) {
        return { target: match, isExternal: false };
      }
      const dotted = absolute.replace(/\//g, ".");
      if (moduleNames.has(dotted)) {
        return { target: dotted, isExternal: false };
      }
    }
    return { target: trimmed, isExternal: !moduleNames.has(trimmed) };
  }
  function normalizePythonDependencies(mod, raw, moduleNames) {
    const parsed = parsePythonImport(mod, raw);
    return parsed.map((entry) => {
      const target = entry.module;
      const symbols = entry.symbols && entry.symbols.length ? mergeSymbols([], entry.symbols) : void 0;
      const isExternal = target ? !moduleNames.has(target) : true;
      return { to: target, symbols, isExternal };
    });
  }
  function normalizeJSImportDependencies(mod, raw, moduleNames, pathToModule) {
    const parsed = parseJSImport(raw);
    return parsed.map((entry) => {
      const resolution = resolveJSImportTarget(mod, entry.module, pathToModule, moduleNames);
      const symbols = entry.symbols && entry.symbols.length ? mergeSymbols([], entry.symbols) : void 0;
      return { to: resolution.target, symbols, isExternal: resolution.isExternal };
    });
  }
  function normalizeGenericDependency(mod, raw, moduleNames, pathToModule) {
    const resolution = resolveJSImportTarget(mod, raw, pathToModule, moduleNames);
    return { to: resolution.target, isExternal: resolution.isExternal };
  }
  function buildDependencyGraph(project) {
    const modules = Object.values(project.modules || {});
    const moduleNames = /* @__PURE__ */ new Set();
    const pathToModule = /* @__PURE__ */ new Map();
    for (const mod of modules) {
      moduleNames.add(mod.name);
      const normalizedPath = normalizePath(mod.path || "");
      if (!normalizedPath) continue;
      const withoutExt = stripExtension(normalizedPath);
      if (withoutExt) {
        pathToModule.set(withoutExt, mod.name);
        if (withoutExt.endsWith("/__init__")) {
          pathToModule.set(withoutExt.replace(/\/__init__$/, ""), mod.name);
        }
        if (withoutExt.endsWith("/index")) {
          pathToModule.set(withoutExt.replace(/\/index$/, ""), mod.name);
        }
      }
    }
    const edgeMap = /* @__PURE__ */ new Map();
    for (const mod of modules) {
      const imports = Array.isArray(mod.imports) ? mod.imports : [];
      if (!imports.length) continue;
      const lang = inferLanguage(mod);
      for (const rawImport of imports) {
        if (typeof rawImport !== "string") continue;
        const trimmed = rawImport.trim();
        if (!trimmed) continue;
        let deps = [];
        if (lang === "python") {
          deps = normalizePythonDependencies(mod, trimmed, moduleNames);
        } else if (lang === "javascript" || lang === "typescript") {
          deps = normalizeJSImportDependencies(mod, trimmed, moduleNames, pathToModule);
        } else {
          deps = normalizePythonDependencies(mod, trimmed, moduleNames);
          if (!deps.length) {
            deps = normalizeJSImportDependencies(mod, trimmed, moduleNames, pathToModule);
          }
          if (!deps.length) {
            deps = [normalizeGenericDependency(mod, trimmed, moduleNames, pathToModule)];
          }
        }
        for (const dep of deps) {
          if (!dep.to) continue;
          const key = `${mod.name}|${dep.to}`;
          const existing = edgeMap.get(key);
          if (existing) {
            existing.symbols = mergeSymbols(existing.symbols, dep.symbols);
            if (!dep.isExternal) {
              existing.isExternal = false;
            }
          } else {
            edgeMap.set(key, {
              from: mod.name,
              to: dep.to,
              symbols: dep.symbols && dep.symbols.length ? [...dep.symbols] : void 0,
              isExternal: dep.isExternal
            });
          }
        }
      }
    }
    const edges = Array.from(edgeMap.values());
    edges.sort((a, b) => {
      const fromCmp = a.from.localeCompare(b.from);
      if (fromCmp !== 0) return fromCmp;
      return a.to.localeCompare(b.to);
    });
    return { edges };
  }

  // engine-src/packages/emitters/mermaid/src/compose.ts
  var DIAGRAM_HEADERS = {
    flowchart: "flowchart TD",
    classDiagram: "classDiagram",
    sequenceDiagram: "sequenceDiagram",
    callGraph: "graph TD",
    dependencyGraph: "graph LR"
  };
  function uniqueFragments(fragments, include, exclude) {
    const seen = /* @__PURE__ */ new Set();
    const filtered = [];
    for (const fragment of fragments) {
      if (include && !include.has(fragment.id)) continue;
      if (exclude && exclude.has(fragment.id)) continue;
      if (seen.has(fragment.id)) continue;
      seen.add(fragment.id);
      filtered.push(fragment);
    }
    return filtered;
  }
  function sortFragments(fragments, sort) {
    if (!fragments.length) return fragments;
    if (!sort || sort === "stable") return fragments;
    const copy = [...fragments];
    if (sort === "id") {
      copy.sort((a, b) => a.id.localeCompare(b.id));
    } else if (sort === "title") {
      copy.sort((a, b) => a.title.localeCompare(b.title));
    }
    return copy;
  }
  function resolveAnchor(fragment, preferred, fallbacks) {
    const anchors = fragment.anchors;
    if (!anchors) return void 0;
    if (preferred && anchors[preferred]) {
      return anchors[preferred];
    }
    for (const key of fallbacks) {
      if (key === preferred) continue;
      const value = anchors[key];
      if (value) return value;
    }
    return void 0;
  }
  function arrowForStyle(style) {
    switch (style) {
      case "dashed":
        return "-.->";
      case "dotted":
        return "..>";
      default:
        return "-->";
    }
  }
  function buildLinkLines(diagram, fragments, links) {
    if (!links || links.length === 0) {
      return [];
    }
    const fragmentMap = /* @__PURE__ */ new Map();
    for (const fragment of fragments) {
      fragmentMap.set(fragment.id, fragment);
    }
    const seen = /* @__PURE__ */ new Set();
    const lines = [];
    for (const link of links) {
      if (link.diagram !== diagram) continue;
      const fromFragment = fragmentMap.get(link.fromFragment);
      const toFragment = fragmentMap.get(link.toFragment);
      if (!fromFragment || !toFragment) continue;
      const fromNode = resolveAnchor(fromFragment, link.fromAnchor, ["exit", "center", "entry"]);
      const toNode = resolveAnchor(toFragment, link.toAnchor, ["entry", "center", "exit"]);
      if (!fromNode || !toNode) continue;
      const arrow = arrowForStyle(link.style);
      const cleanLabel = link.label ? link.label.replace(/[\r\n]+/g, " ").replace(/\s+/g, " ").replace(/[|]/g, "/").trim() : "";
      const labelChunk = cleanLabel ? `|${cleanLabel}|` : "";
      const key = `${fromNode}|${toNode}|${labelChunk}|${arrow}`;
      if (seen.has(key)) continue;
      seen.add(key);
      lines.push(`${fromNode} ${arrow}${labelChunk} ${toNode}`);
    }
    return lines;
  }
  function composeMermaid(diagram, fragments, options) {
    const header = DIAGRAM_HEADERS[diagram] ?? "flowchart TD";
    const include = options?.include?.length ? new Set(options.include) : void 0;
    const exclude = options?.exclude?.length ? new Set(options.exclude) : void 0;
    const unique = uniqueFragments(fragments, include, exclude);
    const ordered = sortFragments(unique, options?.sort);
    const bodySegments = ordered.map((fragment) => fragment.code).filter((code) => code && code.trim().length > 0);
    const linkLines = buildLinkLines(diagram, ordered, options?.links);
    if (bodySegments.length === 0 && linkLines.length === 0) {
      return header;
    }
    const lines = [header];
    if (bodySegments.length > 0) {
      lines.push(bodySegments.join("\n"));
    }
    if (linkLines.length > 0) {
      if (bodySegments.length > 0) {
        lines.push("");
      }
      lines.push(...linkLines);
    }
    return lines.join("\n");
  }

  // engine-src/packages/emitters/mermaid/src/utils.ts
  function esc(s) {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, '\\"');
  }
  function wrap(s, width = 28) {
    const out = [];
    let line = "";
    for (const ch of s) {
      line += ch;
      if (line.length >= width && (/[\s,;:，。！？、\]\)\}]/.test(ch) || line.length >= width + 6)) {
        out.push(line);
        line = "";
      }
    }
    if (line) out.push(line);
    return out.join("\n");
  }
  function trunc(s, max = 240) {
    return s.length <= max ? s : s.slice(0, max - 10) + "...(truncated)";
  }
  function sid(prefix, key) {
    let h = 2166136261 >>> 0;
    for (let i = 0; i < key.length; i++) {
      h ^= key.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return `${prefix}_${(h >>> 0).toString(16)}`;
  }

  // engine-src/packages/emitters/mermaid/src/flowchart.ts
  function buildFunctionFragment(modName, modPath, fn, ctx) {
    const fragmentId = fn.id || `${modName}.${fn.name}`;
    const lines = [`subgraph ${fragmentId}`];
    const cfg = fn.cfg;
    let entryNode;
    let exitNode;
    if (!cfg || cfg.nodes.length === 0) {
      const A = sid("A", fragmentId);
      const B = sid("B", fragmentId);
      lines.push(`${A}((Start))`);
      lines.push(`${B}((End))`);
      lines.push(`${A} --> ${B}`);
      entryNode = A;
      exitNode = B;
    } else {
      for (const n of cfg.nodes) {
        const label = esc(wrap(trunc(n.label || n.kind, 120)));
        const id = sid("N", fragmentId + ":" + n.id);
        switch (n.kind) {
          case "start":
            lines.push(`${id}((Start))`);
            if (!entryNode) entryNode = id;
            break;
          case "end":
            lines.push(`${id}((End))`);
            if (!exitNode) exitNode = id;
            break;
          case "decision":
            lines.push(`${id}{${label}}`);
            break;
          default:
            lines.push(`${id}[${label}]`);
        }
      }
      for (const e of cfg.edges) {
        const a = sid("N", fragmentId + ":" + e.from);
        const b = sid("N", fragmentId + ":" + e.to);
        const lab = e.label ? ` -- ${esc(e.label)} --> ` : " --> ";
        lines.push(`${a}${lab}${b}`);
      }
      if (!entryNode && cfg.nodes.length > 0) {
        entryNode = sid("N", fragmentId + ":" + cfg.nodes[0].id);
      }
      if (!exitNode && cfg.nodes.length > 0) {
        const last = cfg.nodes[cfg.nodes.length - 1];
        exitNode = sid("N", fragmentId + ":" + last.id);
      }
    }
    lines.push("end");
    return {
      id: fragmentId,
      title: ctx?.className ? `${ctx.className}.${fn.name}` : `${modName}.${fn.name}`,
      diagram: "flowchart",
      code: lines.join("\n"),
      source: { module: modName, function: fn.name, class: ctx?.className, path: modPath },
      anchors: entryNode || exitNode ? { entry: entryNode, exit: exitNode } : void 0
    };
  }
  function emitFlowchartFragments(ir) {
    const fragments = [];
    for (const mod of Object.values(ir.modules)) {
      for (const fn of mod.functions) {
        fragments.push(buildFunctionFragment(mod.name, mod.path, fn));
      }
      for (const cls of mod.classes || []) {
        for (const method of cls.methods || []) {
          fragments.push(
            buildFunctionFragment(mod.name, mod.path, method, { className: cls.name })
          );
        }
      }
    }
    if (fragments.length === 0) {
      fragments.push({
        id: "flowchart-empty",
        title: "empty",
        diagram: "flowchart",
        code: "A((Start))-->B((End))"
      });
    }
    return fragments;
  }
  function buildFlowchartLinks(callGraph, fragments) {
    if (!callGraph?.edges?.length) {
      return [];
    }
    const fragmentMap = /* @__PURE__ */ new Map();
    for (const fragment of fragments) {
      fragmentMap.set(fragment.id, fragment);
    }
    const links = [];
    const dedupe = /* @__PURE__ */ new Set();
    for (const edge of callGraph.edges) {
      if (!edge.toId) continue;
      const fromFragment = fragmentMap.get(edge.from);
      const toFragment = fragmentMap.get(edge.toId);
      if (!fromFragment || !toFragment) continue;
      const fromAnchor = fromFragment.anchors?.exit ? "exit" : void 0;
      const toAnchor = toFragment.anchors?.entry ? "entry" : void 0;
      if (!fromAnchor && !toAnchor) continue;
      const key = `${fromFragment.id}|${toFragment.id}|${fromAnchor ?? ""}|${toAnchor ?? ""}|${edge.toName ?? ""}`;
      if (dedupe.has(key)) continue;
      dedupe.add(key);
      links.push({
        diagram: "flowchart",
        fromFragment: fromFragment.id,
        toFragment: toFragment.id,
        fromAnchor,
        toAnchor,
        label: edge.toName && edge.toName !== edge.toId ? edge.toName : void 0,
        style: "solid"
      });
    }
    return links;
  }

  // engine-src/packages/emitters/mermaid/src/classDiagram.ts
  function buildClassFragment(modName, modPath, cls) {
    const lines = [];
    lines.push(`class ${cls.name} {`);
    for (const a of cls.attrs) lines.push(`  +${a}`);
    for (const m of cls.methods) lines.push(`  +${m.name}(${m.params.join(", ")})`);
    lines.push("}");
    for (const b of cls.bases) lines.push(`${b} <|-- ${cls.name}`);
    return {
      id: cls.id,
      title: cls.name,
      diagram: "classDiagram",
      code: lines.join("\n"),
      source: { module: modName, path: modPath }
    };
  }
  function emitClassDiagramFragments(ir) {
    const fragments = [];
    for (const mod of Object.values(ir.modules)) {
      for (const cls of mod.classes) {
        fragments.push(buildClassFragment(mod.name, mod.path, cls));
      }
    }
    if (fragments.length === 0) {
      fragments.push({
        id: "class-empty",
        title: "empty",
        diagram: "classDiagram",
        code: "class _ { }"
      });
    }
    return fragments;
  }

  // engine-src/packages/emitters/mermaid/src/sequence.ts
  function safeId(label) {
    return label.split(".").join("_");
  }
  function emitSequenceFragments(ir) {
    const participantLines = [];
    const seenParticipants = /* @__PURE__ */ new Set();
    for (const mod of Object.values(ir.modules)) {
      for (const fn of mod.functions) {
        const caller = `${mod.name}.${fn.name}`;
        if (!seenParticipants.has(caller)) {
          participantLines.push(`participant ${safeId(caller)} as ${caller}`);
          seenParticipants.add(caller);
        }
      }
    }
    const additionalParticipants = /* @__PURE__ */ new Set();
    if (ir.callGraph) {
      for (const edge of ir.callGraph.edges) {
        if (!seenParticipants.has(edge.toName)) {
          additionalParticipants.add(edge.toName);
        }
      }
    } else {
      for (const mod of Object.values(ir.modules)) {
        for (const fn of mod.functions) {
          for (const call of fn.calls) {
            if (!seenParticipants.has(call)) {
              additionalParticipants.add(call);
            }
          }
        }
      }
    }
    for (const participant of additionalParticipants) {
      participantLines.push(`participant ${safeId(participant)} as ${participant}`);
      seenParticipants.add(participant);
    }
    const messageLines = [];
    if (ir.callGraph) {
      for (const edge of ir.callGraph.edges) {
        const from = safeId(edge.from);
        const to = safeId(edge.toId || edge.toName);
        messageLines.push(`${from}->>${to}: call()`);
      }
    } else {
      for (const mod of Object.values(ir.modules)) {
        for (const fn of mod.functions) {
          const from = safeId(`${mod.name}.${fn.name}`);
          for (const call of fn.calls) {
            messageLines.push(`${from}->>${safeId(call)}: call()`);
          }
        }
      }
    }
    const fragments = [];
    if (participantLines.length > 0) {
      fragments.push({
        id: "sequence-participants",
        title: "Participants",
        diagram: "sequenceDiagram",
        code: participantLines.join("\n")
      });
    }
    if (messageLines.length > 0) {
      fragments.push({
        id: "sequence-messages",
        title: "Messages",
        diagram: "sequenceDiagram",
        code: messageLines.join("\n")
      });
    }
    if (fragments.length === 0) {
      fragments.push({
        id: "sequence-empty",
        title: "empty",
        diagram: "sequenceDiagram",
        code: "Note over X: no data"
      });
    }
    return fragments;
  }

  // engine-src/packages/emitters/mermaid/src/callGraph.ts
  function formatLabel(primary, secondary) {
    const parts = [primary];
    if (secondary && secondary !== primary) {
      parts.push(secondary);
    }
    const formatted = parts.map((part) => wrap(trunc(part, 96), 32)).join("\n");
    return esc(formatted);
  }
  function collectFunctionNodes(ir) {
    const nodes = /* @__PURE__ */ new Map();
    const modules = Object.values(ir.modules || {}).sort((a, b) => a.name.localeCompare(b.name));
    for (const mod of modules) {
      const moduleName = mod.name || mod.path;
      const functions = [...mod.functions || []].sort((a, b) => a.id.localeCompare(b.id));
      for (const fn of functions) {
        const nodeId = sid("call", fn.id);
        const label = formatLabel(moduleName, fn.name);
        nodes.set(fn.id, { nodeId, label, sortKey: `${moduleName}|${fn.name}|${nodeId}` });
      }
      const classes = [...mod.classes || []].sort((a, b) => a.name.localeCompare(b.name));
      for (const cls of classes) {
        const methods = [...cls.methods || []].sort((a, b) => a.id.localeCompare(b.id));
        for (const method of methods) {
          const nodeId = sid("call", method.id);
          const label = formatLabel(moduleName, `${cls.name}.${method.name}`);
          nodes.set(method.id, { nodeId, label, sortKey: `${moduleName}|${cls.name}.${method.name}|${nodeId}` });
        }
      }
    }
    return nodes;
  }
  function ensureExternalNode(externalNodes, toName, toId) {
    const key = toId || toName || "external";
    let existing = externalNodes.get(key);
    if (existing) return existing;
    const labelSource = toName || toId || "external";
    const nodeId = sid("call_ext", key);
    existing = {
      nodeId,
      label: formatLabel(labelSource),
      sortKey: `~external|${labelSource}|${nodeId}`
    };
    externalNodes.set(key, existing);
    return existing;
  }
  function buildEdgeLabel(edgeName, targetId) {
    if (!edgeName) return void 0;
    if (targetId && edgeName === targetId) return void 0;
    return esc(wrap(trunc(edgeName, 96), 32));
  }
  function buildCallGraphEdges(ir, functionNodes) {
    const externalNodes = /* @__PURE__ */ new Map();
    const edgeRecords = [];
    const seen = /* @__PURE__ */ new Set();
    const callEdges = ir.callGraph?.edges || [];
    for (const edge of callEdges) {
      const fromInfo = functionNodes.get(edge.from);
      if (!fromInfo) continue;
      let targetInfo = void 0;
      if (edge.toId && functionNodes.has(edge.toId)) {
        targetInfo = functionNodes.get(edge.toId);
      }
      if (!targetInfo) {
        targetInfo = ensureExternalNode(externalNodes, edge.toName, edge.toId);
      }
      if (!targetInfo) continue;
      const arrow = functionNodes.has(edge.toId || "") ? "-->" : "-.->";
      const edgeLabel = buildEdgeLabel(edge.toName, edge.toId);
      const labelChunk = edgeLabel ? `|${edgeLabel}|` : "";
      const edgeKey = `${fromInfo.nodeId}|${targetInfo.nodeId}|${labelChunk}|${arrow}`;
      if (seen.has(edgeKey)) continue;
      seen.add(edgeKey);
      edgeRecords.push({
        line: `${fromInfo.nodeId} ${arrow}${labelChunk} ${targetInfo.nodeId}`,
        sortKey: `${fromInfo.sortKey}|${targetInfo.sortKey}|${edgeLabel ?? ""}`
      });
    }
    edgeRecords.sort((a, b) => a.sortKey.localeCompare(b.sortKey));
    return { edges: edgeRecords, externals: externalNodes };
  }
  function emitCallGraphFragments(ir) {
    const functionNodes = collectFunctionNodes(ir);
    const { edges, externals } = buildCallGraphEdges(ir, functionNodes);
    const internalNodes = Array.from(functionNodes.values()).sort((a, b) => a.sortKey.localeCompare(b.sortKey));
    const externalNodes = Array.from(externals.values()).sort((a, b) => a.sortKey.localeCompare(b.sortKey));
    const nodeLines = [];
    for (const node of internalNodes) {
      nodeLines.push(`${node.nodeId}["${node.label}"]`);
    }
    for (const node of externalNodes) {
      nodeLines.push(`${node.nodeId}["${node.label}"]`);
    }
    const edgeLines = edges.map((record) => record.line);
    const lines = [];
    if (nodeLines.length) {
      lines.push(...nodeLines);
    }
    if (edgeLines.length) {
      if (lines.length) {
        lines.push("");
      }
      lines.push(...edgeLines);
    }
    if (lines.length === 0) {
      lines.push('callGraphEmpty["No call relationships found"]');
    }
    return [{
      id: "callGraph",
      title: "Call Graph",
      diagram: "callGraph",
      code: lines.join("\n")
    }];
  }

  // engine-src/packages/emitters/mermaid/src/dependencyGraph.ts
  function formatLabel2(primary, secondary) {
    const parts = [primary];
    if (secondary && secondary !== primary) {
      parts.push(secondary);
    }
    const formatted = parts.map((part) => wrap(trunc(part, 96), 32)).join("\n");
    return esc(formatted);
  }
  function collectModuleNodes(ir) {
    const nodes = /* @__PURE__ */ new Map();
    const modules = Object.values(ir.modules || {}).sort((a, b) => a.name.localeCompare(b.name));
    for (const mod of modules) {
      const nodeId = sid("dep", mod.name || mod.path);
      const secondary = mod.path && mod.path !== mod.name ? mod.path : void 0;
      const label = formatLabel2(mod.name, secondary);
      nodes.set(mod.name, { nodeId, label, sortKey: `${mod.name}|${nodeId}` });
    }
    return nodes;
  }
  function ensureDependencyTarget(modules, externals, target, isExternal) {
    if (!target) return void 0;
    const existingInternal = modules.get(target);
    if (existingInternal) {
      return existingInternal;
    }
    const key = target;
    let existing = externals.get(key);
    if (existing) return existing;
    const nodeId = sid("dep_ext", key);
    existing = {
      nodeId,
      label: formatLabel2(target),
      sortKey: `~external|${target}|${nodeId}`,
      external: true
    };
    externals.set(key, existing);
    return existing;
  }
  function buildDependencyEdges(ir, modules) {
    const externals = /* @__PURE__ */ new Map();
    const records = [];
    const seen = /* @__PURE__ */ new Set();
    const depGraph = ir.dependencyGraph?.edges || [];
    for (const edge of depGraph) {
      const fromNode = modules.get(edge.from);
      if (!fromNode) continue;
      const toNode = ensureDependencyTarget(modules, externals, edge.to, edge.isExternal);
      if (!toNode) continue;
      const isExternal = toNode.external ?? edge.isExternal ?? false;
      const arrow = isExternal ? "-.->" : "-->";
      const labelText = edge.symbols && edge.symbols.length ? esc(wrap(trunc(edge.symbols.join(", "), 96), 32)) : void 0;
      const labelChunk = labelText ? `|${labelText}|` : "";
      const key = `${fromNode.nodeId}|${toNode.nodeId}|${labelChunk}|${arrow}`;
      if (seen.has(key)) continue;
      seen.add(key);
      records.push({
        line: `${fromNode.nodeId} ${arrow}${labelChunk} ${toNode.nodeId}`,
        sortKey: `${fromNode.sortKey}|${toNode.sortKey}|${labelText ?? ""}`
      });
    }
    records.sort((a, b) => a.sortKey.localeCompare(b.sortKey));
    return { edges: records, externals };
  }
  function emitDependencyGraphFragments(ir) {
    const moduleNodes = collectModuleNodes(ir);
    const { edges, externals } = buildDependencyEdges(ir, moduleNodes);
    const internalNodes = Array.from(moduleNodes.values()).sort((a, b) => a.sortKey.localeCompare(b.sortKey));
    const externalNodes = Array.from(externals.values()).sort((a, b) => a.sortKey.localeCompare(b.sortKey));
    const nodeLines = [];
    for (const node of internalNodes) {
      nodeLines.push(`${node.nodeId}["${node.label}"]`);
    }
    for (const node of externalNodes) {
      nodeLines.push(`${node.nodeId}["${node.label}"]`);
    }
    const edgeLines = edges.map((record) => record.line);
    const lines = [];
    if (nodeLines.length) {
      lines.push(...nodeLines);
    }
    if (edgeLines.length) {
      if (lines.length) {
        lines.push("");
      }
      lines.push(...edgeLines);
    }
    if (lines.length === 0) {
      lines.push('dependencyGraphEmpty["No dependencies found"]');
    }
    return [{
      id: "dependencyGraph",
      title: "Dependency Graph",
      diagram: "dependencyGraph",
      code: lines.join("\n")
    }];
  }

  // engine-src/packages/fix-rules/mermaid-compat/src/registry.ts
  var rules = [];
  function register(rule) {
    rules.push(rule);
  }
  function list() {
    return rules.sort((a, b) => a.priority - b.priority);
  }

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/01.ensureHeader.ts
  var EnsureHeader = {
    name: "EnsureHeader",
    priority: 10,
    run(code, ctx) {
      const trimmed = code.trim();
      if (!/^(flowchart|classDiagram|sequenceDiagram|stateDiagram|erDiagram)\b/.test(trimmed)) {
        return { code: `flowchart TD
${code}`, notes: ["Added diagram header: flowchart TD"] };
      }
      return { code, notes: [] };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/02.graphToFlowchart.ts
  var GraphToFlowchart = {
    name: "GraphToFlowchart",
    priority: 20,
    run(code, ctx) {
      if (/^graph\s+[A-Z]{2}/mi.test(code)) {
        const c = code.replace(/^graph\s+([A-Z]{2})/gmi, "flowchart $1");
        return { code: c, notes: ["Converted graph to flowchart"] };
      }
      return { code, notes: [] };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/03.normalizeArrows.ts
  var NormalizeArrows = {
    name: "NormalizeArrows",
    priority: 30,
    run(code, ctx) {
      let c = code;
      c = c.replace(/→|—>/g, "-->");
      c = c.replace(/->/g, "-->");
      return { code: c, notes: ["Normalized arrows"] };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/04.escapeLabels.ts
  var EscapeLabels = {
    name: "EscapeLabels",
    priority: 40,
    run(code, ctx) {
      const c = code.replace(/([\[\{])(.*?)([\]\}])/g, (m, a, inner, b) => {
        inner = inner.replace(/\[/g, "\\[").replace(/\]/g, "\\]").replace(/\{/g, "\\{").replace(/\}/g, "\\}").replace(/\|/g, "\\|");
        return `${a}${inner}${b}`;
      });
      return { code: c, notes: ["Escaped bracket-like chars in labels"] };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/05.uniqueIds.ts
  var UniqueIds = {
    name: "UniqueIds",
    priority: 50,
    run(code, ctx) {
      const lines = code.split(/\r?\n/);
      const seen = {};
      const notes = [];
      for (let i = 0; i < lines.length; i++) {
        const m = /^(\w+)\s*(\(|\[|\{)/.exec(lines[i]);
        if (!m) continue;
        const id = m[1];
        seen[id] = (seen[id] ?? 0) + 1;
        if (seen[id] > 1) {
          const newId = `${id}__${seen[id]}`;
          lines[i] = lines[i].replace(id, newId);
          notes.push(`Renamed duplicate id ${id} -> ${newId}`);
        }
      }
      return { code: lines.join("\n"), notes };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/06.ensureParticipants.ts
  var EnsureParticipants = {
    name: "EnsureParticipants",
    priority: 60,
    run(code, ctx) {
      if (ctx.diagram !== "sequenceDiagram") return { code, notes: [] };
      const lines = code.split(/\r?\n/);
      const participants = /* @__PURE__ */ new Set();
      for (const ln of lines) {
        const pm = /^\s*participant\s+([A-Za-z0-9_]+)\b/.exec(ln);
        if (pm) participants.add(pm[1]);
      }
      let changed = false;
      const arrows = Array.from(code.matchAll(/([A-Za-z0-9_]+)->>?([A-Za-z0-9_]+)/g));
      const need = [];
      for (const m of arrows) {
        const a = m[1], b = m[2];
        if (!participants.has(a)) {
          need.push(`participant ${a}`);
          participants.add(a);
          changed = true;
        }
        if (!participants.has(b)) {
          need.push(`participant ${b}`);
          participants.add(b);
          changed = true;
        }
      }
      if (!changed) return { code, notes: [] };
      const out = [];
      let inserted = false;
      for (const ln of lines) {
        out.push(ln);
        if (!inserted && /^\s*sequenceDiagram\b/.test(ln)) {
          for (const n of need) out.push(n);
          inserted = true;
        }
      }
      return { code: out.join("\n"), notes: [`Inserted ${need.length} missing participants`] };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/index.ts
  register(EnsureHeader);
  register(GraphToFlowchart);
  register(NormalizeArrows);
  register(EscapeLabels);
  register(UniqueIds);
  register(EnsureParticipants);
  function applyAll(code, ctx) {
    const notes = [];
    let cur = code;
    for (const r of list()) {
      const res = r.run(cur, ctx);
      cur = res.code;
      if (res.notes.length) notes.push(...res.notes.map((n) => `${r.name}: ${n}`));
    }
    return { code: cur, notes };
  }

  // engine-src/packages/core/src/fallback-parser.ts
  var FALLBACK_PLUGIN_VERSION = "0.1.0";
  var FALLBACK_EXTENSION_MAP = {
    java: [".java"],
    go: [".go"],
    csharp: [".cs"],
    "c#": [".cs"],
    c: [".c", ".h"],
    cpp: [".cc", ".cpp", ".cxx", ".hh", ".hpp"],
    "c++": [".cc", ".cpp", ".cxx", ".hh", ".hpp"],
    "objective-c": [".m", ".mm"],
    objc: [".m", ".mm"],
    swift: [".swift"],
    rust: [".rs"],
    php: [".php"],
    ruby: [".rb"],
    kotlin: [".kt", ".kts"],
    scala: [".scala"],
    dart: [".dart"],
    elixir: [".ex", ".exs"],
    erlang: [".erl", ".hrl"],
    haskell: [".hs"],
    ocaml: [".ml", ".mli"],
    zig: [".zig"],
    nim: [".nim"],
    julia: [".jl"]
  };
  var KEYWORD_EXCLUSIONS = /* @__PURE__ */ new Set([
    "if",
    "for",
    "while",
    "switch",
    "catch",
    "try",
    "else",
    "case",
    "default",
    "with",
    "match",
    "when",
    "loop",
    "macro",
    "typedef",
    "template",
    "function",
    "class",
    "struct",
    "enum"
  ]);
  var FUNCTION_PATTERNS = [
    {
      regex: /\bfunc\s+(?:\([^)]+\)\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)[^{]*\{/gm,
      body: "brace"
    },
    {
      regex: /\bfn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)[^{]*\{/gm,
      body: "brace"
    },
    {
      regex: /\bfunc\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)[^{]*\{/gm,
      body: "brace"
    },
    {
      regex: /\bfunction\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*\{/gm,
      body: "brace"
    },
    {
      regex: /(?:public|protected|private|internal|static|final|async|inline|virtual|override|export|extern|constexpr|friend|mutable|sealed|partial|abstract|synchronized|native|constexpr|using|typename|operator|struct|class|enum|@\w+\s+)*([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*(?:const\s*)?(?:->[^\{\n]+)?\s*\{/gm,
      body: "brace"
    },
    {
      regex: /\bdef\s+([A-Za-z_][A-Za-z0-9_!?=]*)\s*(?:\(([^)]*)\))?/gm,
      body: "none"
    }
  ];
  var CLASS_PATTERNS = [
    /(?:public|protected|private|internal|static|final|abstract|sealed|partial|open|data|@\w+\s+)*(class|struct|interface|enum)\s+([A-Za-z_][A-Za-z0-9_<>]*)[^\{;]*\{/gm,
    /type\s+([A-Za-z_][A-Za-z0-9_]*)\s+struct\s*\{/gm,
    /(?:pub\s+)?struct\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{/gm,
    /(?:pub\s+)?enum\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{/gm,
    /\bclass\s+([A-Za-z_][A-Za-z0-9_:]*)\b/gm
  ];
  function moduleNameFromPath(filePath) {
    return filePath.replace(/\\/g, "/").replace(/\.[^.]+$/i, "").replace(/\//g, ".");
  }
  function lineNumberAt(source, index) {
    let line = 1;
    const limit = Math.min(index, source.length);
    for (let i = 0; i < limit; i += 1) {
      if (source[i] === "\n") {
        line += 1;
      }
    }
    return line;
  }
  function findMatchingBrace(source, openIndex) {
    let depth = 0;
    for (let i = openIndex; i < source.length; i += 1) {
      const ch = source[i];
      if (ch === "{") {
        depth += 1;
      } else if (ch === "}") {
        depth -= 1;
        if (depth === 0) {
          return i;
        }
      }
    }
    return -1;
  }
  function normalizeParams(raw) {
    if (!raw) return [];
    return raw.split(",").map((segment) => {
      let cleaned = segment.trim();
      if (!cleaned) return "";
      cleaned = cleaned.replace(/=[^,]+$/, "").trim();
      const colonIndex = cleaned.indexOf(":");
      if (colonIndex !== -1) {
        cleaned = cleaned.slice(0, colonIndex).trim();
      }
      cleaned = cleaned.replace(/^\.\.\./, "").replace(/\?$/, "");
      const parts = cleaned.split(/\s+/);
      return parts[parts.length - 1] || "";
    }).filter(Boolean);
  }
  function collectCalls(body) {
    const calls = /* @__PURE__ */ new Set();
    const callRe = /([A-Za-z_][A-Za-z0-9_\.]*?)\s*\(/g;
    let match;
    while (match = callRe.exec(body)) {
      const callee = match[1];
      if (!callee || KEYWORD_EXCLUSIONS.has(callee)) continue;
      calls.add(callee);
    }
    return Array.from(calls);
  }
  function extractBases(header) {
    const bases = /* @__PURE__ */ new Set();
    const extendsMatch = header.match(/extends\s+([^\{\n]+)/);
    if (extendsMatch) {
      extendsMatch[1].split(/[,\s]+/).map((part) => part.trim()).filter(Boolean).forEach((base) => bases.add(base));
    }
    const implementsMatch = header.match(/implements\s+([^\{\n]+)/);
    if (implementsMatch) {
      implementsMatch[1].split(/[,\s]+/).map((part) => part.trim()).filter(Boolean).forEach((base) => bases.add(base));
    }
    const colonMatch = header.match(/:\s*([^\{\n]+)/);
    if (colonMatch) {
      colonMatch[1].split(/[,\s]+/).map((part) => part.trim()).filter(Boolean).forEach((base) => bases.add(base));
    }
    const inheritsMatch = header.match(/inherits\s+([^\{\n]+)/);
    if (inheritsMatch) {
      inheritsMatch[1].split(/[,\s]+/).map((part) => part.trim()).filter(Boolean).forEach((base) => bases.add(base));
    }
    return Array.from(bases);
  }
  function extractImports(source) {
    const imports = /* @__PURE__ */ new Set();
    const simpleImportRe = /import\s+(?:[^;\n]+?\s+from\s+)?['"]([^'"\\]+)['"]/g;
    let match;
    while (match = simpleImportRe.exec(source)) {
      imports.add(match[1]);
    }
    const bareImportRe = /import\s+([A-Za-z0-9_\.\*]+)\s*;/g;
    while (match = bareImportRe.exec(source)) {
      imports.add(match[1]);
    }
    const usingRe = /using\s+([A-Za-z0-9_\.]+)\s*;/g;
    while (match = usingRe.exec(source)) {
      imports.add(match[1]);
    }
    const includeRe = /#include\s+[<"]([^>"]+)[>"]/g;
    while (match = includeRe.exec(source)) {
      imports.add(match[1]);
    }
    const requireRe = /require\s*\(\s*['"]([^'"\\]+)['"]\s*\)/g;
    while (match = requireRe.exec(source)) {
      imports.add(match[1]);
    }
    const useRe = /use\s+([A-Za-z0-9_\\]+)\s*;/g;
    while (match = useRe.exec(source)) {
      imports.add(match[1]);
    }
    const goBlockRe = /import\s*\(([^)]+)\)/g;
    while (match = goBlockRe.exec(source)) {
      const block = match[1];
      const inner = block.match(/['"]([^'"\\]+)['"]/g) || [];
      for (const spec of inner) {
        const cleaned = spec.replace(/^['"]|['"]$/g, "");
        if (cleaned) imports.add(cleaned);
      }
    }
    const goSingleRe = /import\s+['"]([^'"\\]+)['"]/g;
    while (match = goSingleRe.exec(source)) {
      imports.add(match[1]);
    }
    return Array.from(imports);
  }
  function extractFunctions(source, context) {
    const results = /* @__PURE__ */ new Map();
    for (const pattern of FUNCTION_PATTERNS) {
      pattern.regex.lastIndex = 0;
      let match;
      while (match = pattern.regex.exec(source)) {
        const name = (match[1] || "").trim();
        if (!name || KEYWORD_EXCLUSIONS.has(name)) {
          continue;
        }
        const paramsRaw = match[2] || "";
        const params = normalizeParams(paramsRaw);
        const relativeIndex = match.index ?? 0;
        const absoluteIndex = (context.absoluteOffset ?? 0) + relativeIndex;
        const line = lineNumberAt(context.parentSource, absoluteIndex);
        let endLine;
        let body = "";
        if (pattern.body === "brace") {
          const localBrace = source.indexOf("{", relativeIndex + match[0].length - 1);
          if (localBrace !== -1) {
            const absoluteBrace = (context.absoluteOffset ?? 0) + localBrace;
            const closeIndex = findMatchingBrace(context.parentSource, absoluteBrace);
            if (closeIndex !== -1) {
              body = context.parentSource.slice(absoluteBrace + 1, closeIndex);
              endLine = lineNumberAt(context.parentSource, closeIndex);
            } else {
              body = context.parentSource.slice(absoluteBrace + 1);
            }
          }
        }
        const calls = collectCalls(body);
        const baseId = context.scope === "class" && context.className ? `${context.className}.${name}` : name;
        const id = `${context.moduleName}.${baseId}`;
        if (results.has(id)) continue;
        results.set(id, {
          id,
          name,
          params,
          body: [],
          calls,
          pos: { file: context.filePath, line, endLine },
          doc: void 0
        });
      }
    }
    return Array.from(results.values());
  }
  function parseModule(filePath, source, lang, moduleName) {
    const moduleFunctions = /* @__PURE__ */ new Map();
    const classes = [];
    const moduleContext = {
      moduleName,
      filePath,
      parentSource: source,
      scope: "module",
      absoluteOffset: 0
    };
    for (const fn of extractFunctions(source, moduleContext)) {
      moduleFunctions.set(fn.id, fn);
    }
    for (const pattern of CLASS_PATTERNS) {
      pattern.lastIndex = 0;
      let match;
      while (match = pattern.exec(source)) {
        const raw = match[0];
        const name = (match[2] || match[1] || "").trim();
        if (!name) continue;
        const classIndex = match.index ?? 0;
        const braceIndex = source.indexOf("{", classIndex + raw.length - 1);
        if (braceIndex === -1) {
          continue;
        }
        const classBodyEnd = findMatchingBrace(source, braceIndex);
        const bodyEnd = classBodyEnd === -1 ? source.length : classBodyEnd;
        const classBody = source.slice(braceIndex + 1, bodyEnd);
        const classLine = lineNumberAt(source, classIndex);
        const methods = extractFunctions(classBody, {
          moduleName,
          filePath,
          parentSource: source,
          scope: "class",
          className: name,
          absoluteOffset: braceIndex + 1
        });
        const bases = extractBases(raw);
        classes.push({
          id: `${moduleName}.${name}`,
          name,
          bases,
          attrs: [],
          methods,
          pos: { file: filePath, line: classLine },
          doc: void 0
        });
      }
    }
    const imports = extractImports(source);
    return {
      name: moduleName,
      path: filePath,
      classes,
      functions: Array.from(moduleFunctions.values()),
      imports
    };
  }
  function filterEntries(files, lang, extensions) {
    const extSet = new Set((extensions && extensions.length ? extensions : FALLBACK_EXTENSION_MAP[lang] || []).map((ext) => ext.toLowerCase()));
    const entries = [];
    for (const [filePath, source] of Object.entries(files)) {
      if (extSet.size === 0) {
        entries.push([filePath, source]);
        continue;
      }
      const ext = path_browser_shim_default.extname(filePath).toLowerCase();
      if (extSet.has(ext)) {
        entries.push([filePath, source]);
      }
    }
    if (entries.length === 0) {
      return Object.entries(files);
    }
    return entries;
  }
  function buildParserMeta(lang, runtime, extensions) {
    const details = { lang };
    if (extensions && extensions.length) {
      details.extensions = extensions;
    }
    return {
      implementation: "fallback",
      runtime,
      details
    };
  }
  function createFallbackParserPlugin(lang, config = {}) {
    const normalized = lang.trim().toLowerCase();
    const extensions = config.extensions && config.extensions.length ? config.extensions : FALLBACK_EXTENSION_MAP[normalized];
    return {
      lang: normalized,
      version: FALLBACK_PLUGIN_VERSION,
      aliases: normalized.includes("#") ? [normalized.replace("#", "sharp")] : void 0,
      parseProject: async (files, options) => {
        if (!files || Object.keys(files).length === 0) {
          throw new Error("No source files provided for fallback parser.");
        }
        const entries = filterEntries(files, normalized, extensions);
        const modules = {};
        for (const [filePath, source] of entries) {
          const moduleName = moduleNameFromPath(filePath);
          modules[moduleName] = parseModule(filePath, source, normalized, moduleName);
        }
        const project = { modules, fixNotes: [] };
        const meta = buildParserMeta(normalized, options?.runtime, extensions);
        project.parserMeta = meta;
        project.fixNotes = project.fixNotes || [];
        project.fixNotes.push(
          `Used generic fallback parser for ${normalized}. Results are heuristic and may be incomplete.`
        );
        return project;
      },
      detect: void 0,
      capabilities: { fallback: true }
    };
  }

  // engine-src/packages/core/src/parsers.ts
  var registry = /* @__PURE__ */ new Map();
  function normalizeLang(lang) {
    return lang.trim().toLowerCase();
  }
  var CONFIDENCE_ORDER = {
    low: 1,
    medium: 2,
    high: 3
  };
  function maxConfidence(a, b) {
    return CONFIDENCE_ORDER[a] >= CONFIDENCE_ORDER[b] ? a : b;
  }
  function scoreConfidence(conf) {
    if (!conf) return 0;
    return CONFIDENCE_ORDER[conf];
  }
  var EXTENSION_HINTS = {
    ".py": { lang: "python", confidence: "high" },
    ".pyi": { lang: "python", confidence: "medium" },
    ".js": { lang: "javascript", confidence: "medium" },
    ".jsx": { lang: "javascript", confidence: "medium" },
    ".ts": { lang: "typescript", confidence: "high" },
    ".tsx": { lang: "typescript", confidence: "medium" },
    ".mjs": { lang: "javascript", confidence: "medium" },
    ".cjs": { lang: "javascript", confidence: "medium" },
    ".java": { lang: "java", confidence: "medium" },
    ".go": { lang: "go", confidence: "medium" },
    ".cs": { lang: "csharp", confidence: "medium" },
    ".rs": { lang: "rust", confidence: "medium" },
    ".rb": { lang: "ruby", confidence: "medium" },
    ".php": { lang: "php", confidence: "medium" },
    ".c": { lang: "c", confidence: "medium" },
    ".h": { lang: "c", confidence: "low" },
    ".cc": { lang: "cpp", confidence: "medium" },
    ".cpp": { lang: "cpp", confidence: "medium" },
    ".cxx": { lang: "cpp", confidence: "medium" },
    ".hh": { lang: "cpp", confidence: "low" },
    ".hpp": { lang: "cpp", confidence: "low" },
    ".m": { lang: "objective-c", confidence: "medium" },
    ".swift": { lang: "swift", confidence: "medium" }
  };
  function collectHeuristicCandidates(files) {
    const byLang = /* @__PURE__ */ new Map();
    for (const filePath of Object.keys(files)) {
      const ext = path_browser_shim_default.extname(filePath).toLowerCase();
      if (!ext) continue;
      const hint = EXTENSION_HINTS[ext];
      if (!hint) continue;
      const lang = normalizeLang(hint.lang);
      let entry = byLang.get(lang);
      if (!entry) {
        entry = {
          count: 0,
          files: [],
          exts: /* @__PURE__ */ new Set(),
          confidence: hint.confidence
        };
        byLang.set(lang, entry);
      } else {
        entry.confidence = maxConfidence(entry.confidence, hint.confidence);
      }
      entry.count += 1;
      entry.exts.add(ext);
      if (entry.files.length < 5) {
        entry.files.push(filePath);
      }
    }
    const heuristics = /* @__PURE__ */ new Map();
    for (const [lang, meta] of byLang) {
      if (meta.count === 0) continue;
      const exts = Array.from(meta.exts.values());
      const reason = meta.count === 1 ? `Found ${exts[0] ?? ""} file ${meta.files[0]}` : `Found ${meta.count} files (${exts.join(", ")})`;
      heuristics.set(lang, {
        count: meta.count,
        extensions: exts,
        detection: {
          lang,
          confidence: meta.confidence,
          reason,
          matchedFiles: meta.files
        }
      });
    }
    return heuristics;
  }
  function isParserPlugin(candidate) {
    return candidate && typeof candidate === "object" && typeof candidate.lang === "string" && typeof candidate.parseProject === "function";
  }
  function extractPlugin(mod) {
    if (!mod) return null;
    const candidate = mod.parserPlugin ?? mod.default ?? mod;
    return isParserPlugin(candidate) ? candidate : null;
  }
  function candidateModuleIds(lang) {
    const normalized = normalizeLang(lang).replace(/[^a-z0-9]+/g, "-");
    const ids = /* @__PURE__ */ new Set();
    ids.add(`@diagrammender/parsers-${normalized}`);
    ids.add(`@diagrammender/parser-${normalized}`);
    ids.add(`@diagrammender/parsers/${normalized}`);
    ids.add(`diagrammender-parser-${normalized}`);
    const localRoot = path_browser_shim_default.join(__dirname, "..", "parsers", normalized);
    ids.add(localRoot);
    ids.add(path_browser_shim_default.join(localRoot, "dist"));
    ids.add(path_browser_shim_default.join(localRoot, "dist", "src"));
    return Array.from(ids);
  }
  var ParserPluginNotFoundError = class extends Error {
    constructor(lang, attempted) {
      const fallback = attempted.length ? `Tried dynamic module ids: ${attempted.join(", ")}` : "No dynamic module ids were generated for this language.";
      super(
        `Parser plugin not found for language "${lang}". Install the appropriate @diagrammender/parsers-* package or provide a manual parser.
` + fallback
      );
      this.name = "ParserPluginNotFoundError";
      this.lang = lang;
      this.attempted = attempted;
    }
  };
  function tryRequire(moduleId) {
    try {
      const mod = __require(moduleId);
      return extractPlugin(mod);
    } catch (err) {
      if (err && err.code === "MODULE_NOT_FOUND") {
        const msg = typeof err.message === "string" ? err.message : "";
        if (msg.includes(moduleId)) {
          return null;
        }
      }
      throw err;
    }
  }
  function registerParserPlugin(plugin) {
    const primary = normalizeLang(plugin.lang);
    registry.set(primary, plugin);
    if (plugin.aliases) {
      for (const alias of plugin.aliases) {
        registry.set(normalizeLang(alias), plugin);
      }
    }
    return plugin;
  }
  async function loadParserPlugin(lang) {
    const normalized = normalizeLang(lang);
    const existing = registry.get(normalized);
    if (existing) return existing;
    const attempted = [];
    for (const moduleId of candidateModuleIds(normalized)) {
      attempted.push(moduleId);
      const plugin = tryRequire(moduleId);
      if (plugin) {
        registerParserPlugin(plugin);
        registry.set(normalized, plugin);
        return plugin;
      }
    }
    throw new ParserPluginNotFoundError(lang, attempted);
  }
  async function resolveParserPlugin(options) {
    const {
      lang,
      files,
      candidates = [],
      detect = true,
      allowHeuristics = true
    } = options;
    if (lang && lang !== "auto") {
      const normalizedLang = normalizeLang(lang);
      const heuristics2 = files && allowHeuristics ? collectHeuristicCandidates(files) : void 0;
      let plugin;
      let detection;
      try {
        plugin = await loadParserPlugin(lang);
      } catch (err) {
        if (err instanceof ParserPluginNotFoundError) {
          const fallback = createFallbackParserPlugin(normalizedLang, {
            extensions: heuristics2?.get(normalizedLang)?.extensions
          });
          plugin = registerParserPlugin(fallback);
          detection = heuristics2?.get(normalizedLang)?.detection;
        } else {
          throw err;
        }
      }
      if (!detection && detect && files && typeof plugin.detect === "function") {
        detection = plugin.detect(files) ?? void 0;
      }
      if (!detection && heuristics2) {
        detection = heuristics2.get(normalizeLang(plugin.lang))?.detection;
      }
      return { plugin, detection };
    }
    if (!files) {
      throw new Error("resolveParserPlugin requires files when language is not specified.");
    }
    const heuristics = allowHeuristics ? collectHeuristicCandidates(files) : /* @__PURE__ */ new Map();
    const candidatesByLang = /* @__PURE__ */ new Map();
    for (const cand of candidates) {
      candidatesByLang.set(normalizeLang(cand), {});
    }
    for (const [langId, heuristic] of heuristics) {
      candidatesByLang.set(langId, { heuristic });
    }
    if (candidatesByLang.size === 0) {
      throw new Error("Unable to detect parser language from provided files. Specify lang explicitly.");
    }
    const resolutions = [];
    const missing = [];
    for (const [langId, meta] of candidatesByLang) {
      let plugin;
      try {
        plugin = await loadParserPlugin(langId);
      } catch (err) {
        if (err instanceof ParserPluginNotFoundError) {
          missing.push(err.lang);
        }
        continue;
      }
      let detection;
      if (detect && typeof plugin.detect === "function") {
        try {
          const result = plugin.detect(files);
          if (result) detection = { ...result, lang: normalizeLang(plugin.lang) };
        } catch (e) {
        }
      }
      if (!detection && meta.heuristic) {
        detection = meta.heuristic.detection;
      } else if (detection && meta.heuristic) {
        if (!detection.matchedFiles || detection.matchedFiles.length === 0) {
          detection = {
            ...detection,
            matchedFiles: meta.heuristic.detection.matchedFiles
          };
        }
        if (!detection.reason && meta.heuristic.detection.reason) {
          detection = {
            ...detection,
            reason: meta.heuristic.detection.reason
          };
        }
      }
      const score = scoreConfidence(detection?.confidence) * 100 + (meta.heuristic?.count ?? 0);
      resolutions.push({ plugin, detection, score });
    }
    if (resolutions.length === 0) {
      if (missing.length) {
        const langId = normalizeLang(missing[0]);
        const heuristic = heuristics.get(langId);
        const fallback = registerParserPlugin(
          createFallbackParserPlugin(langId, {
            extensions: heuristic?.extensions
          })
        );
        return { plugin: fallback, detection: heuristic?.detection };
      }
      const hinted = Array.from(candidatesByLang.keys());
      if (hinted.length) {
        throw new Error(`No parser plugin available for detected languages: ${hinted.join(", ")}`);
      }
      throw new Error("No parser plugin could be resolved.");
    }
    resolutions.sort((a, b) => b.score - a.score);
    const best = resolutions[0];
    return { plugin: best.plugin, detection: best.detection };
  }

  // engine-src/packages/core/src/pipeline.ts
  async function runPipeline(files, opts) {
    const trace = [];
    const now = () => Date.now();
    const detectStart = now();
    const { plugin, detection } = await resolveParserPlugin({
      lang: opts.lang,
      files,
      detect: opts.detect !== false,
      candidates: opts.candidateLangs
    });
    trace.push({
      stage: "detect",
      startedAt: detectStart,
      durationMs: now() - detectStart,
      details: detection ? `resolved ${detection.lang} (${detection.confidence})` : `explicit ${plugin.lang}`,
      meta: {
        plugin: plugin.lang,
        version: plugin.version,
        detection
      }
    });
    const parseStart = now();
    const ir = await plugin.parseProject(files, opts.parserOptions);
    trace.push({
      stage: "parse",
      startedAt: parseStart,
      durationMs: now() - parseStart,
      meta: {
        modules: Object.keys(ir.modules ?? {}).length,
        capabilities: plugin.capabilities
      }
    });
    const analyzeStart = now();
    let functionCount = 0;
    let methodCount = 0;
    let classCount = 0;
    for (const mod of Object.values(ir.modules)) {
      classCount += mod.classes?.length ?? 0;
      for (const fn of mod.functions) {
        functionCount += 1;
        fn.cfg = buildCFG(fn);
      }
      for (const cls of mod.classes || []) {
        for (const method of cls.methods || []) {
          functionCount += 1;
          methodCount += 1;
          method.cfg = buildCFG(method);
        }
      }
    }
    ir.callGraph = buildCallGraph(ir);
    ir.dependencyGraph = buildDependencyGraph(ir);
    trace.push({
      stage: "analyze",
      startedAt: analyzeStart,
      durationMs: now() - analyzeStart,
      meta: {
        functions: functionCount,
        methods: methodCount,
        classes: classCount,
        callEdges: ir.callGraph?.edges.length ?? 0,
        dependencyEdges: ir.dependencyGraph?.edges.length ?? 0
      }
    });
    const diagram = opts.diagram;
    const emitStart = now();
    let fragments = [];
    switch (diagram) {
      case "flowchart":
        fragments = emitFlowchartFragments(ir);
        break;
      case "classDiagram":
        fragments = emitClassDiagramFragments(ir);
        break;
      case "sequenceDiagram":
        fragments = emitSequenceFragments(ir);
        break;
      case "callGraph":
        fragments = emitCallGraphFragments(ir);
        break;
      case "dependencyGraph":
        fragments = emitDependencyGraphFragments(ir);
        break;
      default:
        fragments = emitFlowchartFragments(ir);
        break;
    }
    const links = diagram === "flowchart" ? buildFlowchartLinks(ir.callGraph, fragments) : [];
    const rawCode = composeMermaid(diagram, fragments, { links });
    trace.push({
      stage: "emit",
      startedAt: emitStart,
      durationMs: now() - emitStart,
      meta: {
        diagram,
        fragments: fragments.length,
        links: links.length,
        rawLength: rawCode.length
      }
    });
    const fixStart = now();
    const fixDiagram = diagram === "flowchart" || diagram === "classDiagram" || diagram === "sequenceDiagram" ? diagram : "flowchart";
    const { code: fixed, notes } = applyAll(rawCode, { diagram: fixDiagram, mermaidVersion: opts.mermaidVersion ?? "v11" });
    trace.push({
      stage: "fix",
      startedAt: fixStart,
      durationMs: now() - fixStart,
      meta: {
        notes: notes.length,
        delta: fixed.length - rawCode.length
      }
    });
    if (notes.length) {
      ir.fixNotes = (ir.fixNotes || []).concat(notes);
    }
    return { code: fixed, notes, plugin, detection, ir, rawCode, fragments, links, trace };
  }

  // engine-src/packages/core/src/browser-entry.ts
  var ENGINE_VERSION = "0.3.0";
  var ENGINE_SOURCE = `browser-core@${ENGINE_VERSION}`;
  function normalizeDiagram(diagram) {
    switch (diagram) {
      case "sequenceDiagram":
      case "classDiagram":
      case "callGraph":
      case "dependencyGraph":
        return diagram;
      default:
        return "flowchart";
    }
  }
  function normalizeParserOptions(options) {
    const normalized = { ...options };
    normalized.runtime = "browser";
    if (normalized.preferTreeSitter === false) {
      return normalized;
    }
    if (normalized.webTreeSitter) {
      normalized.preferTreeSitter = true;
    } else if (typeof normalized.preferTreeSitter === "undefined") {
      normalized.preferTreeSitter = true;
    }
    return normalized;
  }
  function normalizePipelineOptions(diagram, options) {
    const candidateLangs = Array.isArray(options?.candidateLangs) ? options?.candidateLangs : void 0;
    const parserOptions = normalizeParserOptions(options?.parserOptions);
    const mermaidVersion = options?.mermaidVersion === "v10" ? "v10" : "v11";
    return {
      diagram,
      lang: typeof options?.lang === "string" ? options.lang : void 0,
      detect: options?.detect !== false,
      candidateLangs,
      parserOptions,
      mermaidVersion
    };
  }
  function sanitizePlugin(plugin) {
    if (!plugin) return null;
    const info = {
      lang: plugin.lang,
      version: plugin.version
    };
    if (Array.isArray(plugin.aliases)) info.aliases = [...plugin.aliases];
    if (plugin.capabilities) info.capabilities = { ...plugin.capabilities };
    if (typeof plugin.treeSitterModule === "string") info.treeSitterModule = plugin.treeSitterModule;
    return info;
  }
  function buildLogEntries(result, diagram) {
    const entries = [];
    if (result.detection) {
      entries.push({
        rule: "pipeline.detect",
        msg: `detected ${result.detection.lang} (${result.detection.confidence})`,
        meta: { ...result.detection }
      });
    }
    if (result.ir?.parserMeta) {
      const meta = result.ir.parserMeta;
      if (meta.implementation === "web-tree-sitter") {
        entries.push({ rule: "worker.wts", msg: "web-tree-sitter used", meta: { ...meta } });
      } else if (meta.implementation === "tree-sitter") {
        entries.push({
          rule: "pipeline.parser",
          msg: `tree-sitter (${meta.runtime ?? "node"})`,
          meta: { ...meta }
        });
      } else if (meta.implementation === "fallback") {
        entries.push({
          rule: "pipeline.parser",
          msg: "fallback parser used",
          meta: { ...meta }
        });
      }
    }
    for (const entry of result.trace || []) {
      entries.push({
        rule: `pipeline.${entry.stage}`,
        msg: `${entry.stage} (${Math.round(entry.durationMs)} ms)`,
        meta: {
          ...entry.meta,
          details: entry.details
        }
      });
    }
    if (result.notes?.length) {
      for (const note of result.notes) {
        entries.push({ rule: "pipeline.fixNote", msg: note });
      }
    }
    entries.push({
      rule: "pipeline.diagram",
      msg: `composed ${diagram} with ${result.fragments.length} fragment(s)` + (diagram === "flowchart" ? ` and ${result.links.length} link(s)` : "")
    });
    return entries;
  }
  function createBrowserResult(diagram, pipeline, extras = {}) {
    return {
      code: pipeline.code,
      dtype: diagram,
      errors: [],
      log: buildLogEntries(pipeline, diagram),
      fragments: pipeline.fragments,
      links: pipeline.links,
      rawCode: pipeline.rawCode,
      notes: pipeline.notes,
      detection: pipeline.detection,
      plugin: sanitizePlugin(pipeline.plugin),
      trace: pipeline.trace,
      ir: pipeline.ir,
      engine: { source: ENGINE_SOURCE, version: ENGINE_VERSION },
      ...extras
    };
  }
  async function runPipeline2(files, options = {}) {
    const diagram = normalizeDiagram(options.diagram || options.mode || options.dtype);
    const pipelineOptions = normalizePipelineOptions(diagram, options);
    const pipelineResult = await runPipeline(files || {}, pipelineOptions);
    return createBrowserResult(diagram, pipelineResult);
  }
  function ensureAnalysis(ir) {
    for (const mod of Object.values(ir.modules || {})) {
      for (const fn of mod.functions || []) {
        if (!fn.cfg) {
          fn.cfg = buildCFG(fn);
        }
      }
      for (const cls of mod.classes || []) {
        for (const method of cls.methods || []) {
          if (!method.cfg) {
            method.cfg = buildCFG(method);
          }
        }
      }
    }
    if (!ir.callGraph || !Array.isArray(ir.callGraph.edges)) {
      ir.callGraph = buildCallGraph(ir);
    }
    if (!ir.dependencyGraph || !Array.isArray(ir.dependencyGraph.edges)) {
      ir.dependencyGraph = buildDependencyGraph(ir);
    }
  }
  async function runPipelineIR(ir, options = {}) {
    const diagram = normalizeDiagram(options.diagram || options.mode || options.dtype);
    const project = ir || { modules: {} };
    ensureAnalysis(project);
    let fragments = [];
    switch (diagram) {
      case "classDiagram":
        fragments = emitClassDiagramFragments(project);
        break;
      case "sequenceDiagram":
        fragments = emitSequenceFragments(project);
        break;
      case "callGraph":
        fragments = emitCallGraphFragments(project);
        break;
      case "dependencyGraph":
        fragments = emitDependencyGraphFragments(project);
        break;
      default:
        fragments = emitFlowchartFragments(project);
        break;
    }
    const links = diagram === "flowchart" ? buildFlowchartLinks(project.callGraph, fragments) : [];
    const rawCode = composeMermaid(diagram, fragments, { links });
    const mermaidVersion = options?.mermaidVersion === "v10" ? "v10" : "v11";
    const fixDiagram = diagram === "flowchart" || diagram === "classDiagram" || diagram === "sequenceDiagram" ? diagram : "flowchart";
    const { code, notes } = applyAll(rawCode, { diagram: fixDiagram, mermaidVersion });
    const trace = [
      {
        stage: "emit",
        startedAt: Date.now(),
        durationMs: 0,
        details: "runPipelineIR emit",
        meta: {
          diagram,
          fragments: fragments.length,
          links: links.length
        }
      },
      {
        stage: "fix",
        startedAt: Date.now(),
        durationMs: 0,
        details: "runPipelineIR fix",
        meta: {
          notes: notes.length
        }
      }
    ];
    const pipelineLike = {
      code,
      notes,
      plugin: {
        lang: typeof options?.lang === "string" ? options.lang : "ir",
        version: "ir",
        parseProject: () => project
      },
      detection: void 0,
      ir: project,
      rawCode,
      fragments,
      links,
      trace
    };
    return createBrowserResult(diagram, pipelineLike);
  }
  var DiagramMenderCore = {
    runPipeline: runPipeline2,
    runPipelineIR,
    composeMermaid,
    version: ENGINE_SOURCE
  };
  if (typeof globalThis !== "undefined") {
    globalThis.DiagramMenderCore = DiagramMenderCore;
  }
  var browser_entry_default = DiagramMenderCore;
})();
