// Auto-generated by scripts/build-engine-browser.mjs

"use strict";
(() => {
  var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
    get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
  }) : x)(function(x) {
    if (typeof require !== "undefined") return require.apply(this, arguments);
    throw Error('Dynamic require of "' + x + '" is not supported');
  });

  // engine-src/packages/analyzers/src/cfg.ts
  var idc = 0;
  function nid(prefix) {
    idc += 1;
    return `${prefix}_${idc}`;
  }
  function buildCFG(fn) {
    idc = 0;
    const nodes = [];
    const edges = [];
    const start = nid("start");
    const end = nid("end");
    nodes.push({ id: start, kind: "start", label: "Start" });
    nodes.push({ id: end, kind: "end", label: "End" });
    function seq(stmts) {
      if (!stmts || stmts.length === 0) {
        const x = nid("op");
        nodes.push({ id: x, kind: "op", label: "pass" });
        return { entry: x, exits: [x] };
      }
      let first = null;
      let prevExits = [];
      for (const s of stmts) {
        const { entry, exits } = build(s);
        if (!first) first = entry;
        for (const p of prevExits) edges.push({ from: p, to: entry });
        prevExits = exits;
      }
      return { entry: first, exits: prevExits };
    }
    function build(s) {
      switch (s.kind) {
        case "if": {
          const d = nid("dec");
          nodes.push({ id: d, kind: "decision", label: `if ${s.cond}?` });
          const t = seq(s.then || []);
          edges.push({ from: d, to: t.entry, label: "True" });
          const e = s.else ? seq(s.else) : { entry: d, exits: [d] };
          if (s.else) edges.push({ from: d, to: e.entry, label: "False" });
          const m = nid("merge");
          nodes.push({ id: m, kind: "merge", label: "merge" });
          for (const x of t.exits) edges.push({ from: x, to: m });
          for (const x of e.exits) edges.push({ from: x, to: m });
          return { entry: d, exits: [m] };
        }
        case "for": {
          const d = nid("loop");
          nodes.push({ id: d, kind: "loop", label: `for ${s.target} in ${s.iter}` });
          const b = seq(s.body || []);
          edges.push({ from: d, to: b.entry, label: "loop" });
          for (const x of b.exits) edges.push({ from: x, to: d, label: "next" });
          const m = nid("merge");
          nodes.push({ id: m, kind: "merge", label: "exit" });
          edges.push({ from: d, to: m, label: "exit" });
          return { entry: d, exits: [m] };
        }
        case "while": {
          const d = nid("dec");
          nodes.push({ id: d, kind: "decision", label: `while ${s.cond}?` });
          const b = seq(s.body || []);
          edges.push({ from: d, to: b.entry, label: "True" });
          for (const x of b.exits) edges.push({ from: x, to: d, label: "loop" });
          const m = nid("merge");
          nodes.push({ id: m, kind: "merge", label: "False" });
          edges.push({ from: d, to: m, label: "False" });
          return { entry: d, exits: [m] };
        }
        case "try": {
          const t = seq(s.body || []);
          const d = nid("try");
          nodes.push({ id: d, kind: "try", label: "try" });
          edges.push({ from: d, to: t.entry });
          const merges = [];
          for (const h of s.excepts || []) {
            const hb = seq(h.body || []);
            const ex = nid("ex");
            nodes.push({ id: ex, kind: "except", label: `except ${h.type || ""}` });
            edges.push({ from: d, to: hb.entry });
            merges.push(...hb.exits);
          }
          const m = nid("merge");
          nodes.push({ id: m, kind: "merge", label: "merge" });
          for (const x of t.exits.concat(merges)) edges.push({ from: x, to: m });
          return { entry: d, exits: [m] };
        }
        default: {
          const n = nid("op");
          nodes.push({ id: n, kind: "op", label: s.text || s.kind });
          if (s.kind === "return" || s.kind === "raise") {
            edges.push({ from: n, to: end });
            return { entry: n, exits: [end] };
          }
          return { entry: n, exits: [n] };
        }
      }
    }
    if (!fn.body || fn.body.length === 0) {
      edges.push({ from: start, to: end });
    } else {
      const { entry, exits } = seq(fn.body);
      edges.push({ from: start, to: entry });
      for (const x of exits) edges.push({ from: x, to: end });
    }
    return { nodes, edges };
  }

  // engine-src/packages/analyzers/src/calls.ts
  function buildCallGraph(project) {
    const edges = [];
    const nameToId = /* @__PURE__ */ new Map();
    const register2 = (name, id) => {
      if (!name) return;
      const normalized = name.replace(/::/g, ".");
      if (!nameToId.has(normalized)) {
        nameToId.set(normalized, id);
      }
    };
    for (const mod of Object.values(project.modules)) {
      for (const fn of mod.functions) {
        register2(fn.id, fn.id);
        register2(`${mod.name}.${fn.name}`, fn.id);
        register2(fn.name, fn.id);
      }
      for (const cls of mod.classes || []) {
        for (const method of cls.methods || []) {
          register2(method.id, method.id);
          register2(`${mod.name}.${method.name}`, method.id);
          register2(`${cls.name}.${method.name}`, method.id);
          register2(`${mod.name}.${cls.name}.${method.name}`, method.id);
          register2(method.name, method.id);
        }
      }
    }
    const resolveTarget = (rawName) => {
      if (!rawName) return void 0;
      const normalized = rawName.replace(/::/g, ".");
      const direct = nameToId.get(normalized);
      if (direct) return direct;
      const parts = normalized.split(".");
      for (let i = 0; i < parts.length; i += 1) {
        const suffix = parts.slice(i).join(".");
        const match = nameToId.get(suffix);
        if (match) return match;
      }
      return void 0;
    };
    for (const mod of Object.values(project.modules)) {
      for (const fn of mod.functions) {
        for (const callee of fn.calls || []) {
          const toId = resolveTarget(callee);
          edges.push({ from: fn.id, toName: callee, toId });
        }
      }
      for (const cls of mod.classes || []) {
        for (const method of cls.methods || []) {
          for (const callee of method.calls || []) {
            const toId = resolveTarget(callee);
            edges.push({ from: method.id, toName: callee, toId });
          }
        }
      }
    }
    return { edges };
  }

  // engine-src/packages/emitters/mermaid/src/compose.ts
  var DIAGRAM_HEADERS = {
    flowchart: "flowchart TD",
    classDiagram: "classDiagram",
    sequenceDiagram: "sequenceDiagram"
  };
  function uniqueFragments(fragments, include, exclude) {
    const seen = /* @__PURE__ */ new Set();
    const filtered = [];
    for (const fragment of fragments) {
      if (include && !include.has(fragment.id)) continue;
      if (exclude && exclude.has(fragment.id)) continue;
      if (seen.has(fragment.id)) continue;
      seen.add(fragment.id);
      filtered.push(fragment);
    }
    return filtered;
  }
  function sortFragments(fragments, sort) {
    if (!fragments.length) return fragments;
    if (!sort || sort === "stable") return fragments;
    const copy = [...fragments];
    if (sort === "id") {
      copy.sort((a, b) => a.id.localeCompare(b.id));
    } else if (sort === "title") {
      copy.sort((a, b) => a.title.localeCompare(b.title));
    }
    return copy;
  }
  function resolveAnchor(fragment, preferred, fallbacks) {
    const anchors = fragment.anchors;
    if (!anchors) return void 0;
    if (preferred && anchors[preferred]) {
      return anchors[preferred];
    }
    for (const key of fallbacks) {
      if (key === preferred) continue;
      const value = anchors[key];
      if (value) return value;
    }
    return void 0;
  }
  function arrowForStyle(style) {
    switch (style) {
      case "dashed":
        return "-.->";
      case "dotted":
        return "..>";
      default:
        return "-->";
    }
  }
  function buildLinkLines(diagram, fragments, links) {
    if (!links || links.length === 0) {
      return [];
    }
    const fragmentMap = /* @__PURE__ */ new Map();
    for (const fragment of fragments) {
      fragmentMap.set(fragment.id, fragment);
    }
    const seen = /* @__PURE__ */ new Set();
    const lines = [];
    for (const link of links) {
      if (link.diagram !== diagram) continue;
      const fromFragment = fragmentMap.get(link.fromFragment);
      const toFragment = fragmentMap.get(link.toFragment);
      if (!fromFragment || !toFragment) continue;
      const fromNode = resolveAnchor(fromFragment, link.fromAnchor, ["exit", "center", "entry"]);
      const toNode = resolveAnchor(toFragment, link.toAnchor, ["entry", "center", "exit"]);
      if (!fromNode || !toNode) continue;
      const arrow = arrowForStyle(link.style);
      const cleanLabel = link.label ? link.label.replace(/[\r\n]+/g, " ").replace(/\s+/g, " ").replace(/[|]/g, "/").trim() : "";
      const labelChunk = cleanLabel ? `|${cleanLabel}|` : "";
      const key = `${fromNode}|${toNode}|${labelChunk}|${arrow}`;
      if (seen.has(key)) continue;
      seen.add(key);
      lines.push(`${fromNode} ${arrow}${labelChunk} ${toNode}`);
    }
    return lines;
  }
  function composeMermaid(diagram, fragments, options) {
    const header = DIAGRAM_HEADERS[diagram] ?? "flowchart TD";
    const include = options?.include?.length ? new Set(options.include) : void 0;
    const exclude = options?.exclude?.length ? new Set(options.exclude) : void 0;
    const unique = uniqueFragments(fragments, include, exclude);
    const ordered = sortFragments(unique, options?.sort);
    const bodySegments = ordered.map((fragment) => fragment.code).filter((code) => code && code.trim().length > 0);
    const linkLines = buildLinkLines(diagram, ordered, options?.links);
    if (bodySegments.length === 0 && linkLines.length === 0) {
      return header;
    }
    const lines = [header];
    if (bodySegments.length > 0) {
      lines.push(bodySegments.join("\n"));
    }
    if (linkLines.length > 0) {
      if (bodySegments.length > 0) {
        lines.push("");
      }
      lines.push(...linkLines);
    }
    return lines.join("\n");
  }

  // engine-src/packages/emitters/mermaid/src/utils.ts
  function esc(s) {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, '\\"');
  }
  function wrap(s, width = 28) {
    const out = [];
    let line = "";
    for (const ch of s) {
      line += ch;
      if (line.length >= width && (/[\s,;:，。！？、\]\)\}]/.test(ch) || line.length >= width + 6)) {
        out.push(line);
        line = "";
      }
    }
    if (line) out.push(line);
    return out.join("\n");
  }
  function trunc(s, max = 240) {
    return s.length <= max ? s : s.slice(0, max - 10) + "...(truncated)";
  }
  function sid(prefix, key) {
    let h = 2166136261 >>> 0;
    for (let i = 0; i < key.length; i++) {
      h ^= key.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return `${prefix}_${(h >>> 0).toString(16)}`;
  }

  // engine-src/packages/emitters/mermaid/src/flowchart.ts
  function buildFunctionFragment(modName, modPath, fn, ctx) {
    const fragmentId = fn.id || `${modName}.${fn.name}`;
    const lines = [`subgraph ${fragmentId}`];
    const cfg = fn.cfg;
    let entryNode;
    let exitNode;
    if (!cfg || cfg.nodes.length === 0) {
      const A = sid("A", fragmentId);
      const B = sid("B", fragmentId);
      lines.push(`${A}((Start))`);
      lines.push(`${B}((End))`);
      lines.push(`${A} --> ${B}`);
      entryNode = A;
      exitNode = B;
    } else {
      for (const n of cfg.nodes) {
        const label = esc(wrap(trunc(n.label || n.kind, 120)));
        const id = sid("N", fragmentId + ":" + n.id);
        switch (n.kind) {
          case "start":
            lines.push(`${id}((Start))`);
            if (!entryNode) entryNode = id;
            break;
          case "end":
            lines.push(`${id}((End))`);
            if (!exitNode) exitNode = id;
            break;
          case "decision":
            lines.push(`${id}{${label}}`);
            break;
          default:
            lines.push(`${id}[${label}]`);
        }
      }
      for (const e of cfg.edges) {
        const a = sid("N", fragmentId + ":" + e.from);
        const b = sid("N", fragmentId + ":" + e.to);
        const lab = e.label ? ` -- ${esc(e.label)} --> ` : " --> ";
        lines.push(`${a}${lab}${b}`);
      }
      if (!entryNode && cfg.nodes.length > 0) {
        entryNode = sid("N", fragmentId + ":" + cfg.nodes[0].id);
      }
      if (!exitNode && cfg.nodes.length > 0) {
        const last = cfg.nodes[cfg.nodes.length - 1];
        exitNode = sid("N", fragmentId + ":" + last.id);
      }
    }
    lines.push("end");
    return {
      id: fragmentId,
      title: ctx?.className ? `${ctx.className}.${fn.name}` : `${modName}.${fn.name}`,
      diagram: "flowchart",
      code: lines.join("\n"),
      source: { module: modName, function: fn.name, class: ctx?.className, path: modPath },
      anchors: entryNode || exitNode ? { entry: entryNode, exit: exitNode } : void 0
    };
  }
  function emitFlowchartFragments(ir) {
    const fragments = [];
    for (const mod of Object.values(ir.modules)) {
      for (const fn of mod.functions) {
        fragments.push(buildFunctionFragment(mod.name, mod.path, fn));
      }
      for (const cls of mod.classes || []) {
        for (const method of cls.methods || []) {
          fragments.push(
            buildFunctionFragment(mod.name, mod.path, method, { className: cls.name })
          );
        }
      }
    }
    if (fragments.length === 0) {
      fragments.push({
        id: "flowchart-empty",
        title: "empty",
        diagram: "flowchart",
        code: "A((Start))-->B((End))"
      });
    }
    return fragments;
  }
  function buildFlowchartLinks(callGraph, fragments) {
    if (!callGraph?.edges?.length) {
      return [];
    }
    const fragmentMap = /* @__PURE__ */ new Map();
    for (const fragment of fragments) {
      fragmentMap.set(fragment.id, fragment);
    }
    const links = [];
    const dedupe = /* @__PURE__ */ new Set();
    for (const edge of callGraph.edges) {
      if (!edge.toId) continue;
      const fromFragment = fragmentMap.get(edge.from);
      const toFragment = fragmentMap.get(edge.toId);
      if (!fromFragment || !toFragment) continue;
      const fromAnchor = fromFragment.anchors?.exit ? "exit" : void 0;
      const toAnchor = toFragment.anchors?.entry ? "entry" : void 0;
      if (!fromAnchor && !toAnchor) continue;
      const key = `${fromFragment.id}|${toFragment.id}|${fromAnchor ?? ""}|${toAnchor ?? ""}|${edge.toName ?? ""}`;
      if (dedupe.has(key)) continue;
      dedupe.add(key);
      links.push({
        diagram: "flowchart",
        fromFragment: fromFragment.id,
        toFragment: toFragment.id,
        fromAnchor,
        toAnchor,
        label: edge.toName && edge.toName !== edge.toId ? edge.toName : void 0,
        style: "solid"
      });
    }
    return links;
  }

  // engine-src/packages/emitters/mermaid/src/classDiagram.ts
  function buildClassFragment(modName, modPath, cls) {
    const lines = [];
    lines.push(`class ${cls.name} {`);
    for (const a of cls.attrs) lines.push(`  +${a}`);
    for (const m of cls.methods) lines.push(`  +${m.name}(${m.params.join(", ")})`);
    lines.push("}");
    for (const b of cls.bases) lines.push(`${b} <|-- ${cls.name}`);
    return {
      id: cls.id,
      title: cls.name,
      diagram: "classDiagram",
      code: lines.join("\n"),
      source: { module: modName, path: modPath }
    };
  }
  function emitClassDiagramFragments(ir) {
    const fragments = [];
    for (const mod of Object.values(ir.modules)) {
      for (const cls of mod.classes) {
        fragments.push(buildClassFragment(mod.name, mod.path, cls));
      }
    }
    if (fragments.length === 0) {
      fragments.push({
        id: "class-empty",
        title: "empty",
        diagram: "classDiagram",
        code: "class _ { }"
      });
    }
    return fragments;
  }

  // engine-src/packages/emitters/mermaid/src/sequence.ts
  function safeId(label) {
    return label.split(".").join("_");
  }
  function emitSequenceFragments(ir) {
    const participantLines = [];
    const seenParticipants = /* @__PURE__ */ new Set();
    for (const mod of Object.values(ir.modules)) {
      for (const fn of mod.functions) {
        const caller = `${mod.name}.${fn.name}`;
        if (!seenParticipants.has(caller)) {
          participantLines.push(`participant ${safeId(caller)} as ${caller}`);
          seenParticipants.add(caller);
        }
      }
    }
    const additionalParticipants = /* @__PURE__ */ new Set();
    if (ir.callGraph) {
      for (const edge of ir.callGraph.edges) {
        if (!seenParticipants.has(edge.toName)) {
          additionalParticipants.add(edge.toName);
        }
      }
    } else {
      for (const mod of Object.values(ir.modules)) {
        for (const fn of mod.functions) {
          for (const call of fn.calls) {
            if (!seenParticipants.has(call)) {
              additionalParticipants.add(call);
            }
          }
        }
      }
    }
    for (const participant of additionalParticipants) {
      participantLines.push(`participant ${safeId(participant)} as ${participant}`);
      seenParticipants.add(participant);
    }
    const messageLines = [];
    if (ir.callGraph) {
      for (const edge of ir.callGraph.edges) {
        const from = safeId(edge.from);
        const to = safeId(edge.toId || edge.toName);
        messageLines.push(`${from}->>${to}: call()`);
      }
    } else {
      for (const mod of Object.values(ir.modules)) {
        for (const fn of mod.functions) {
          const from = safeId(`${mod.name}.${fn.name}`);
          for (const call of fn.calls) {
            messageLines.push(`${from}->>${safeId(call)}: call()`);
          }
        }
      }
    }
    const fragments = [];
    if (participantLines.length > 0) {
      fragments.push({
        id: "sequence-participants",
        title: "Participants",
        diagram: "sequenceDiagram",
        code: participantLines.join("\n")
      });
    }
    if (messageLines.length > 0) {
      fragments.push({
        id: "sequence-messages",
        title: "Messages",
        diagram: "sequenceDiagram",
        code: messageLines.join("\n")
      });
    }
    if (fragments.length === 0) {
      fragments.push({
        id: "sequence-empty",
        title: "empty",
        diagram: "sequenceDiagram",
        code: "Note over X: no data"
      });
    }
    return fragments;
  }

  // engine-src/packages/fix-rules/mermaid-compat/src/registry.ts
  var rules = [];
  function register(rule) {
    rules.push(rule);
  }
  function list() {
    return rules.sort((a, b) => a.priority - b.priority);
  }

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/01.ensureHeader.ts
  var EnsureHeader = {
    name: "EnsureHeader",
    priority: 10,
    run(code, ctx) {
      const trimmed = code.trim();
      if (!/^(flowchart|classDiagram|sequenceDiagram|stateDiagram|erDiagram)\b/.test(trimmed)) {
        return { code: `flowchart TD
${code}`, notes: ["Added diagram header: flowchart TD"] };
      }
      return { code, notes: [] };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/02.graphToFlowchart.ts
  var GraphToFlowchart = {
    name: "GraphToFlowchart",
    priority: 20,
    run(code, ctx) {
      if (/^graph\s+[A-Z]{2}/mi.test(code)) {
        const c = code.replace(/^graph\s+([A-Z]{2})/gmi, "flowchart $1");
        return { code: c, notes: ["Converted graph to flowchart"] };
      }
      return { code, notes: [] };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/03.normalizeArrows.ts
  var NormalizeArrows = {
    name: "NormalizeArrows",
    priority: 30,
    run(code, ctx) {
      let c = code;
      c = c.replace(/→|—>/g, "-->");
      c = c.replace(/->/g, "-->");
      return { code: c, notes: ["Normalized arrows"] };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/04.escapeLabels.ts
  var EscapeLabels = {
    name: "EscapeLabels",
    priority: 40,
    run(code, ctx) {
      const c = code.replace(/([\[\{])(.*?)([\]\}])/g, (m, a, inner, b) => {
        inner = inner.replace(/\[/g, "\\[").replace(/\]/g, "\\]").replace(/\{/g, "\\{").replace(/\}/g, "\\}").replace(/\|/g, "\\|");
        return `${a}${inner}${b}`;
      });
      return { code: c, notes: ["Escaped bracket-like chars in labels"] };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/05.uniqueIds.ts
  var UniqueIds = {
    name: "UniqueIds",
    priority: 50,
    run(code, ctx) {
      const lines = code.split(/\r?\n/);
      const seen = {};
      const notes = [];
      for (let i = 0; i < lines.length; i++) {
        const m = /^(\w+)\s*(\(|\[|\{)/.exec(lines[i]);
        if (!m) continue;
        const id = m[1];
        seen[id] = (seen[id] ?? 0) + 1;
        if (seen[id] > 1) {
          const newId = `${id}__${seen[id]}`;
          lines[i] = lines[i].replace(id, newId);
          notes.push(`Renamed duplicate id ${id} -> ${newId}`);
        }
      }
      return { code: lines.join("\n"), notes };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/rules/06.ensureParticipants.ts
  var EnsureParticipants = {
    name: "EnsureParticipants",
    priority: 60,
    run(code, ctx) {
      if (ctx.diagram !== "sequenceDiagram") return { code, notes: [] };
      const lines = code.split(/\r?\n/);
      const participants = /* @__PURE__ */ new Set();
      for (const ln of lines) {
        const pm = /^\s*participant\s+([A-Za-z0-9_]+)\b/.exec(ln);
        if (pm) participants.add(pm[1]);
      }
      let changed = false;
      const arrows = Array.from(code.matchAll(/([A-Za-z0-9_]+)->>?([A-Za-z0-9_]+)/g));
      const need = [];
      for (const m of arrows) {
        const a = m[1], b = m[2];
        if (!participants.has(a)) {
          need.push(`participant ${a}`);
          participants.add(a);
          changed = true;
        }
        if (!participants.has(b)) {
          need.push(`participant ${b}`);
          participants.add(b);
          changed = true;
        }
      }
      if (!changed) return { code, notes: [] };
      const out = [];
      let inserted = false;
      for (const ln of lines) {
        out.push(ln);
        if (!inserted && /^\s*sequenceDiagram\b/.test(ln)) {
          for (const n of need) out.push(n);
          inserted = true;
        }
      }
      return { code: out.join("\n"), notes: [`Inserted ${need.length} missing participants`] };
    }
  };

  // engine-src/packages/fix-rules/mermaid-compat/src/index.ts
  register(EnsureHeader);
  register(GraphToFlowchart);
  register(NormalizeArrows);
  register(EscapeLabels);
  register(UniqueIds);
  register(EnsureParticipants);
  function applyAll(code, ctx) {
    const notes = [];
    let cur = code;
    for (const r of list()) {
      const res = r.run(cur, ctx);
      cur = res.code;
      if (res.notes.length) notes.push(...res.notes.map((n) => `${r.name}: ${n}`));
    }
    return { code: cur, notes };
  }

  // scripts/lib/path-browser-shim.js
  function extname(input = "") {
    const normalized = String(input);
    const lastDot = normalized.lastIndexOf(".");
    const lastSlash = Math.max(normalized.lastIndexOf("/"), normalized.lastIndexOf("\\"));
    if (lastDot <= lastSlash) return "";
    return normalized.slice(lastDot);
  }
  function join(...segments) {
    const parts = segments.flatMap((segment) => String(segment || "").split(/[\\/]+/)).filter(Boolean);
    let joined = parts.join("/");
    if (segments.length && String(segments[0] || "").startsWith("/")) {
      joined = `/${joined}`;
    }
    return joined || ".";
  }
  var path_browser_shim_default = { extname, join };

  // engine-src/packages/core/src/parsers.ts
  var registry = /* @__PURE__ */ new Map();
  function normalizeLang(lang) {
    return lang.trim().toLowerCase();
  }
  var CONFIDENCE_ORDER = {
    low: 1,
    medium: 2,
    high: 3
  };
  function maxConfidence(a, b) {
    return CONFIDENCE_ORDER[a] >= CONFIDENCE_ORDER[b] ? a : b;
  }
  function scoreConfidence(conf) {
    if (!conf) return 0;
    return CONFIDENCE_ORDER[conf];
  }
  var EXTENSION_HINTS = {
    ".py": { lang: "python", confidence: "high" },
    ".pyi": { lang: "python", confidence: "medium" },
    ".js": { lang: "javascript", confidence: "medium" },
    ".jsx": { lang: "javascript", confidence: "medium" },
    ".ts": { lang: "typescript", confidence: "high" },
    ".tsx": { lang: "typescript", confidence: "medium" },
    ".mjs": { lang: "javascript", confidence: "medium" },
    ".cjs": { lang: "javascript", confidence: "medium" },
    ".java": { lang: "java", confidence: "medium" },
    ".go": { lang: "go", confidence: "medium" },
    ".cs": { lang: "csharp", confidence: "medium" },
    ".rs": { lang: "rust", confidence: "medium" },
    ".rb": { lang: "ruby", confidence: "medium" },
    ".php": { lang: "php", confidence: "medium" },
    ".c": { lang: "c", confidence: "medium" },
    ".h": { lang: "c", confidence: "low" },
    ".cc": { lang: "cpp", confidence: "medium" },
    ".cpp": { lang: "cpp", confidence: "medium" },
    ".cxx": { lang: "cpp", confidence: "medium" },
    ".hh": { lang: "cpp", confidence: "low" },
    ".hpp": { lang: "cpp", confidence: "low" },
    ".m": { lang: "objective-c", confidence: "medium" },
    ".swift": { lang: "swift", confidence: "medium" }
  };
  function collectHeuristicCandidates(files) {
    const byLang = /* @__PURE__ */ new Map();
    for (const filePath of Object.keys(files)) {
      const ext = path_browser_shim_default.extname(filePath).toLowerCase();
      if (!ext) continue;
      const hint = EXTENSION_HINTS[ext];
      if (!hint) continue;
      const lang = normalizeLang(hint.lang);
      let entry = byLang.get(lang);
      if (!entry) {
        entry = {
          count: 0,
          files: [],
          exts: /* @__PURE__ */ new Set(),
          confidence: hint.confidence
        };
        byLang.set(lang, entry);
      } else {
        entry.confidence = maxConfidence(entry.confidence, hint.confidence);
      }
      entry.count += 1;
      entry.exts.add(ext);
      if (entry.files.length < 5) {
        entry.files.push(filePath);
      }
    }
    const heuristics = /* @__PURE__ */ new Map();
    for (const [lang, meta] of byLang) {
      if (meta.count === 0) continue;
      const exts = Array.from(meta.exts.values());
      const reason = meta.count === 1 ? `Found ${exts[0] ?? ""} file ${meta.files[0]}` : `Found ${meta.count} files (${exts.join(", ")})`;
      heuristics.set(lang, {
        count: meta.count,
        detection: {
          lang,
          confidence: meta.confidence,
          reason,
          matchedFiles: meta.files
        }
      });
    }
    return heuristics;
  }
  function isParserPlugin(candidate) {
    return candidate && typeof candidate === "object" && typeof candidate.lang === "string" && typeof candidate.parseProject === "function";
  }
  function extractPlugin(mod) {
    if (!mod) return null;
    const candidate = mod.parserPlugin ?? mod.default ?? mod;
    return isParserPlugin(candidate) ? candidate : null;
  }
  function candidateModuleIds(lang) {
    const normalized = normalizeLang(lang).replace(/[^a-z0-9]+/g, "-");
    const ids = /* @__PURE__ */ new Set();
    ids.add(`@diagrammender/parsers-${normalized}`);
    ids.add(`@diagrammender/parser-${normalized}`);
    ids.add(`@diagrammender/parsers/${normalized}`);
    ids.add(`diagrammender-parser-${normalized}`);
    const localRoot = path_browser_shim_default.join(__dirname, "..", "parsers", normalized);
    ids.add(localRoot);
    ids.add(path_browser_shim_default.join(localRoot, "dist"));
    ids.add(path_browser_shim_default.join(localRoot, "dist", "src"));
    return Array.from(ids);
  }
  function tryRequire(moduleId) {
    try {
      const mod = __require(moduleId);
      return extractPlugin(mod);
    } catch (err) {
      if (err && err.code === "MODULE_NOT_FOUND") {
        const msg = typeof err.message === "string" ? err.message : "";
        if (msg.includes(moduleId)) {
          return null;
        }
      }
      throw err;
    }
  }
  function registerParserPlugin(plugin) {
    const primary = normalizeLang(plugin.lang);
    registry.set(primary, plugin);
    if (plugin.aliases) {
      for (const alias of plugin.aliases) {
        registry.set(normalizeLang(alias), plugin);
      }
    }
    return plugin;
  }
  async function loadParserPlugin(lang) {
    const normalized = normalizeLang(lang);
    const existing = registry.get(normalized);
    if (existing) return existing;
    for (const moduleId of candidateModuleIds(normalized)) {
      const plugin = tryRequire(moduleId);
      if (plugin) {
        registerParserPlugin(plugin);
        registry.set(normalized, plugin);
        return plugin;
      }
    }
    throw new Error(`Parser plugin not found for language: ${lang}`);
  }
  async function resolveParserPlugin(options) {
    const {
      lang,
      files,
      candidates = [],
      detect = true,
      allowHeuristics = true
    } = options;
    if (lang && lang !== "auto") {
      const plugin = await loadParserPlugin(lang);
      let detection;
      if (detect && files && typeof plugin.detect === "function") {
        detection = plugin.detect(files) ?? void 0;
      }
      if (!detection && files && allowHeuristics) {
        detection = collectHeuristicCandidates(files).get(normalizeLang(plugin.lang))?.detection;
      }
      return { plugin, detection };
    }
    if (!files) {
      throw new Error("resolveParserPlugin requires files when language is not specified.");
    }
    const heuristics = allowHeuristics ? collectHeuristicCandidates(files) : /* @__PURE__ */ new Map();
    const candidatesByLang = /* @__PURE__ */ new Map();
    for (const cand of candidates) {
      candidatesByLang.set(normalizeLang(cand), {});
    }
    for (const [langId, heuristic] of heuristics) {
      candidatesByLang.set(langId, { heuristic });
    }
    if (candidatesByLang.size === 0) {
      throw new Error("Unable to detect parser language from provided files. Specify lang explicitly.");
    }
    const resolutions = [];
    for (const [langId, meta] of candidatesByLang) {
      let plugin;
      try {
        plugin = await loadParserPlugin(langId);
      } catch (err) {
        continue;
      }
      let detection;
      if (detect && typeof plugin.detect === "function") {
        try {
          const result = plugin.detect(files);
          if (result) detection = { ...result, lang: normalizeLang(plugin.lang) };
        } catch (e) {
        }
      }
      if (!detection && meta.heuristic) {
        detection = meta.heuristic.detection;
      } else if (detection && meta.heuristic) {
        if (!detection.matchedFiles || detection.matchedFiles.length === 0) {
          detection = {
            ...detection,
            matchedFiles: meta.heuristic.detection.matchedFiles
          };
        }
        if (!detection.reason && meta.heuristic.detection.reason) {
          detection = {
            ...detection,
            reason: meta.heuristic.detection.reason
          };
        }
      }
      const score = scoreConfidence(detection?.confidence) * 100 + (meta.heuristic?.count ?? 0);
      resolutions.push({ plugin, detection, score });
    }
    if (resolutions.length === 0) {
      const hinted = Array.from(candidatesByLang.keys());
      if (hinted.length) {
        throw new Error(`No parser plugin available for detected languages: ${hinted.join(", ")}`);
      }
      throw new Error("No parser plugin could be resolved.");
    }
    resolutions.sort((a, b) => b.score - a.score);
    const best = resolutions[0];
    return { plugin: best.plugin, detection: best.detection };
  }

  // engine-src/packages/core/src/pipeline.ts
  async function runPipeline(files, opts) {
    const trace = [];
    const now = () => Date.now();
    const detectStart = now();
    const { plugin, detection } = await resolveParserPlugin({
      lang: opts.lang,
      files,
      detect: opts.detect !== false,
      candidates: opts.candidateLangs
    });
    trace.push({
      stage: "detect",
      startedAt: detectStart,
      durationMs: now() - detectStart,
      details: detection ? `resolved ${detection.lang} (${detection.confidence})` : `explicit ${plugin.lang}`,
      meta: {
        plugin: plugin.lang,
        version: plugin.version,
        detection
      }
    });
    const parseStart = now();
    const ir = await plugin.parseProject(files, opts.parserOptions);
    trace.push({
      stage: "parse",
      startedAt: parseStart,
      durationMs: now() - parseStart,
      meta: {
        modules: Object.keys(ir.modules ?? {}).length,
        capabilities: plugin.capabilities
      }
    });
    const analyzeStart = now();
    let functionCount = 0;
    let methodCount = 0;
    let classCount = 0;
    for (const mod of Object.values(ir.modules)) {
      classCount += mod.classes?.length ?? 0;
      for (const fn of mod.functions) {
        functionCount += 1;
        fn.cfg = buildCFG(fn);
      }
      for (const cls of mod.classes || []) {
        for (const method of cls.methods || []) {
          functionCount += 1;
          methodCount += 1;
          method.cfg = buildCFG(method);
        }
      }
    }
    ir.callGraph = buildCallGraph(ir);
    trace.push({
      stage: "analyze",
      startedAt: analyzeStart,
      durationMs: now() - analyzeStart,
      meta: {
        functions: functionCount,
        methods: methodCount,
        classes: classCount,
        callEdges: ir.callGraph?.edges.length ?? 0
      }
    });
    const diagram = opts.diagram;
    const emitStart = now();
    let fragments = [];
    switch (diagram) {
      case "flowchart":
        fragments = emitFlowchartFragments(ir);
        break;
      case "classDiagram":
        fragments = emitClassDiagramFragments(ir);
        break;
      case "sequenceDiagram":
        fragments = emitSequenceFragments(ir);
        break;
      default:
        fragments = emitFlowchartFragments(ir);
        break;
    }
    const links = diagram === "flowchart" ? buildFlowchartLinks(ir.callGraph, fragments) : [];
    const rawCode = composeMermaid(diagram, fragments, { links });
    trace.push({
      stage: "emit",
      startedAt: emitStart,
      durationMs: now() - emitStart,
      meta: {
        diagram,
        fragments: fragments.length,
        links: links.length,
        rawLength: rawCode.length
      }
    });
    const fixStart = now();
    const { code: fixed, notes } = applyAll(rawCode, { diagram, mermaidVersion: opts.mermaidVersion ?? "v11" });
    trace.push({
      stage: "fix",
      startedAt: fixStart,
      durationMs: now() - fixStart,
      meta: {
        notes: notes.length,
        delta: fixed.length - rawCode.length
      }
    });
    if (notes.length) {
      ir.fixNotes = (ir.fixNotes || []).concat(notes);
    }
    return { code: fixed, notes, plugin, detection, ir, rawCode, fragments, links, trace };
  }

  // engine-src/packages/core/src/browser-entry.ts
  var ENGINE_VERSION = "0.3.0";
  var ENGINE_SOURCE = `browser-core@${ENGINE_VERSION}`;
  function normalizeDiagram(diagram) {
    switch (diagram) {
      case "sequenceDiagram":
      case "classDiagram":
        return diagram;
      default:
        return "flowchart";
    }
  }
  function normalizeParserOptions(options) {
    const normalized = { ...options };
    normalized.runtime = "browser";
    normalized.preferTreeSitter = false;
    return normalized;
  }
  function normalizePipelineOptions(diagram, options) {
    const candidateLangs = Array.isArray(options?.candidateLangs) ? options?.candidateLangs : void 0;
    const parserOptions = normalizeParserOptions(options?.parserOptions);
    const mermaidVersion = options?.mermaidVersion === "v10" ? "v10" : "v11";
    return {
      diagram,
      lang: typeof options?.lang === "string" ? options.lang : void 0,
      detect: options?.detect !== false,
      candidateLangs,
      parserOptions,
      mermaidVersion
    };
  }
  function sanitizePlugin(plugin) {
    if (!plugin) return null;
    const info = {
      lang: plugin.lang,
      version: plugin.version
    };
    if (Array.isArray(plugin.aliases)) info.aliases = [...plugin.aliases];
    if (plugin.capabilities) info.capabilities = { ...plugin.capabilities };
    if (typeof plugin.treeSitterModule === "string") info.treeSitterModule = plugin.treeSitterModule;
    return info;
  }
  function buildLogEntries(result, diagram) {
    const entries = [];
    if (result.detection) {
      entries.push({
        rule: "pipeline.detect",
        msg: `detected ${result.detection.lang} (${result.detection.confidence})`,
        meta: { ...result.detection }
      });
    }
    for (const entry of result.trace || []) {
      entries.push({
        rule: `pipeline.${entry.stage}`,
        msg: `${entry.stage} (${Math.round(entry.durationMs)} ms)`,
        meta: {
          ...entry.meta,
          details: entry.details
        }
      });
    }
    if (result.notes?.length) {
      for (const note of result.notes) {
        entries.push({ rule: "pipeline.fixNote", msg: note });
      }
    }
    entries.push({
      rule: "pipeline.diagram",
      msg: `composed ${diagram} with ${result.fragments.length} fragment(s)` + (diagram === "flowchart" ? ` and ${result.links.length} link(s)` : "")
    });
    return entries;
  }
  function createBrowserResult(diagram, pipeline, extras = {}) {
    return {
      code: pipeline.code,
      dtype: diagram,
      errors: [],
      log: buildLogEntries(pipeline, diagram),
      fragments: pipeline.fragments,
      links: pipeline.links,
      rawCode: pipeline.rawCode,
      notes: pipeline.notes,
      detection: pipeline.detection,
      plugin: sanitizePlugin(pipeline.plugin),
      trace: pipeline.trace,
      ir: pipeline.ir,
      engine: { source: ENGINE_SOURCE, version: ENGINE_VERSION },
      ...extras
    };
  }
  async function runPipeline2(files, options = {}) {
    const diagram = normalizeDiagram(options.diagram || options.mode || options.dtype);
    const pipelineOptions = normalizePipelineOptions(diagram, options);
    const pipelineResult = await runPipeline(files || {}, pipelineOptions);
    return createBrowserResult(diagram, pipelineResult);
  }
  function ensureAnalysis(ir) {
    for (const mod of Object.values(ir.modules || {})) {
      for (const fn of mod.functions || []) {
        if (!fn.cfg) {
          fn.cfg = buildCFG(fn);
        }
      }
      for (const cls of mod.classes || []) {
        for (const method of cls.methods || []) {
          if (!method.cfg) {
            method.cfg = buildCFG(method);
          }
        }
      }
    }
    if (!ir.callGraph || !Array.isArray(ir.callGraph.edges)) {
      ir.callGraph = buildCallGraph(ir);
    }
  }
  async function runPipelineIR(ir, options = {}) {
    const diagram = normalizeDiagram(options.diagram || options.mode || options.dtype);
    const project = ir || { modules: {} };
    ensureAnalysis(project);
    let fragments = [];
    switch (diagram) {
      case "classDiagram":
        fragments = emitClassDiagramFragments(project);
        break;
      case "sequenceDiagram":
        fragments = emitSequenceFragments(project);
        break;
      default:
        fragments = emitFlowchartFragments(project);
        break;
    }
    const links = diagram === "flowchart" ? buildFlowchartLinks(project.callGraph, fragments) : [];
    const rawCode = composeMermaid(diagram, fragments, { links });
    const mermaidVersion = options?.mermaidVersion === "v10" ? "v10" : "v11";
    const { code, notes } = applyAll(rawCode, { diagram, mermaidVersion });
    const trace = [
      {
        stage: "emit",
        startedAt: Date.now(),
        durationMs: 0,
        details: "runPipelineIR emit",
        meta: {
          diagram,
          fragments: fragments.length,
          links: links.length
        }
      },
      {
        stage: "fix",
        startedAt: Date.now(),
        durationMs: 0,
        details: "runPipelineIR fix",
        meta: {
          notes: notes.length
        }
      }
    ];
    const pipelineLike = {
      code,
      notes,
      plugin: {
        lang: typeof options?.lang === "string" ? options.lang : "ir",
        version: "ir",
        parseProject: () => project
      },
      detection: void 0,
      ir: project,
      rawCode,
      fragments,
      links,
      trace
    };
    return createBrowserResult(diagram, pipelineLike);
  }
  var DiagramMenderCore = {
    runPipeline: runPipeline2,
    runPipelineIR,
    composeMermaid,
    version: ENGINE_SOURCE
  };
  if (typeof globalThis !== "undefined") {
    globalThis.DiagramMenderCore = DiagramMenderCore;
  }
  var browser_entry_default = DiagramMenderCore;
})();
