/* eslint-disable no-unused-vars */

// js/engine/emitter.js - Mermaid 生成器增強版
// 支援多種圖表類型，基於 IR 生成高品質的 Mermaid 圖表

import { findEntity } from './ir.js';

/**
 * 基於 IR 生成各種類型的 Mermaid 圖表
 * @param {Object} ir - IR 物件
 * @param {string} diagramType - 圖表類型: 'class', 'flowchart', 'dependency', 'call'
 * @param {Object} options - 生成選項
 * @returns {Object} { code: string, notes: string[], stats: Object }
 */
export function generateMermaidDiagram(ir, diagramType = 'class', options = {}) {
  const generator = getGenerator(diagramType);
  if (!generator) {
    throw new Error(`Unsupported diagram type: ${diagramType}`);
  }

  const result = generator(ir, options);
  
  return {
    code: result.code,
    notes: result.notes || [],
    stats: {
      entities: ir.entities.length,
      relations: ir.relations.length,
      diagramType,
      generatedAt: new Date().toISOString()
    }
  };
}

/**
 * 獲取對應的圖表生成器
 */
function getGenerator(diagramType) {
  const generators = {
    'class': generateClassDiagram,
    'classDiagram': generateClassDiagram,
    'flowchart': generateFlowchart,
    'dependency': generateDependencyGraph,
    'call': generateCallGraph,
    'sequence': generateSequenceDiagram
  };

  return generators[diagramType];
}

/**
 * 生成類別圖
 */
function generateClassDiagram(ir, options = {}) {
  const lines = ['classDiagram'];
  const notes = [];
  const processedClasses = new Set();

  // 過濾並排序類別
  const classes = ir.entities.filter(e => e.kind === 'class');
  const sortedClasses = options.sortAlphabetically ? 
    classes.sort((a, b) => a.name.localeCompare(b.name)) : 
    classes;

  // 生成類別定義
  for (const classEntity of sortedClasses) {
    if (processedClasses.has(classEntity.name)) continue;
    
    lines.push(`    class ${sanitizeName(classEntity.name)} {`);
    
    // 加入屬性（如果有的話）
    const properties = getClassProperties(ir, classEntity);
    for (const prop of properties) {
      lines.push(`        ${prop}`);
    }
    
    // 加入方法
    const methods = getClassMethods(ir, classEntity);
    for (const method of methods) {
      lines.push(`        ${method.name}()`);
    }
    
    lines.push('    }');
    processedClasses.add(classEntity.name);
  }

  // 生成關係
  const relations = ir.relations.filter(r => 
    ['EXTENDS', 'IMPLEMENTS', 'USES', 'DEPENDS_ON'].includes(r.type)
  );

  for (const rel of relations) {
    const fromEntity = findEntity(ir, rel.from);
    const toEntity = findEntity(ir, rel.to);
    
    if (fromEntity && toEntity && 
        fromEntity.kind === 'class' && toEntity.kind === 'class') {
      
      const relationSymbol = getRelationSymbol(rel.type);
      lines.push(`    ${sanitizeName(toEntity.name)} ${relationSymbol} ${sanitizeName(fromEntity.name)}`);
    }
  }

  // 加入註解（如果啟用）
  if (options.includeNotes) {
    lines.push('');
    lines.push('    %% Generated by AutoFix_Mermaid');
    lines.push(`    %% Classes: ${classes.length}, Relations: ${relations.length}`);
  }

  if (classes.length === 0) {
    notes.push('no_classes_found');
  }

  return { code: lines.join('\n'), notes };
}

/**
 * 生成流程圖
 */
function generateFlowchart(ir, options = {}) {
  const direction = options.direction || 'TD';
  const lines = [`flowchart ${direction}`];
  const notes = [];

  // 獲取所有函數和模組
  const functions = ir.entities.filter(e => e.kind === 'function' || e.kind === 'method');
  const modules = ir.entities.filter(e => e.kind === 'module');

  // 生成節點
  for (const func of functions) {
    const nodeId = sanitizeId(func.id);
    const nodeName = func.name;
    lines.push(`    ${nodeId}["${nodeName}"]`);
  }

  // 生成連線（基於呼叫關係）
  const callRelations = ir.relations.filter(r => r.type === 'CALLS');
  for (const rel of callRelations) {
    const fromId = sanitizeId(rel.from);
    const toId = sanitizeId(rel.to);
    lines.push(`    ${fromId} --> ${toId}`);
  }

  // 如果沒有關係，建立基本的模組連結
  if (callRelations.length === 0 && modules.length > 1) {
    for (let i = 0; i < modules.length - 1; i++) {
      const fromId = sanitizeId(modules[i].id);
      const toId = sanitizeId(modules[i + 1].id);
      lines.push(`    ${fromId} --> ${toId}`);
    }
    notes.push('basic_module_flow_generated');
  }

  if (functions.length === 0) {
    notes.push('no_functions_found');
  }

  return { code: lines.join('\n'), notes };
}

/**
 * 生成依賴關係圖
 */
function generateDependencyGraph(ir, options = {}) {
  const lines = ['flowchart LR'];
  const notes = [];

  // 獲取所有模組
  const modules = ir.entities.filter(e => e.kind === 'module');
  const imports = ir.relations.filter(r => 
    r.type === 'IMPORTS' || r.type === 'REQUIRES'
  );

  // 生成模組節點
  for (const module of modules) {
    const nodeId = sanitizeId(module.id);
    const moduleName = module.name;
    lines.push(`    ${nodeId}["${moduleName}"]`);
  }

  // 生成依賴關係
  for (const imp of imports) {
    const fromEntity = findEntity(ir, imp.from);
    const fromId = sanitizeId(imp.from);
    
    // 創建目標模組節點（如果不存在）
    const targetModule = imp.to;
    const targetId = sanitizeId(`module:${targetModule}`);
    
    // 檢查是否為外部依賴
    const isExternal = !modules.some(m => m.name === targetModule);
    if (isExternal) {
      lines.push(`    ${targetId}["${targetModule}"]:::external`);
    }
    
    lines.push(`    ${fromId} --> ${targetId}`);
  }

  // 加入樣式
  lines.push('');
  lines.push('    classDef external fill:#f9f,stroke:#333,stroke-width:2px');

  if (imports.length === 0) {
    notes.push('no_dependencies_found');
  }

  return { code: lines.join('\n'), notes };
}

/**
 * 生成呼叫關係圖
 */
function generateCallGraph(ir, options = {}) {
  const lines = ['flowchart TD'];
  const notes = [];

  // 獲取所有函數和方法
  const functions = ir.entities.filter(e => 
    e.kind === 'function' || e.kind === 'method'
  );
  
  const callRelations = ir.relations.filter(r => r.type === 'CALLS');

  // 生成函數節點
  for (const func of functions) {
    const nodeId = sanitizeId(func.id);
    const shape = func.kind === 'method' ? '{}' : '[]';
    const nodeName = func.data?.class ? 
      `${func.data.class}.${func.name}` : 
      func.name;
    
    lines.push(`    ${nodeId}${shape[0]}"${nodeName}"${shape[1]}`);
  }

  // 生成呼叫關係
  for (const rel of callRelations) {
    const fromId = sanitizeId(rel.from);
    const toId = sanitizeId(rel.to);
    lines.push(`    ${fromId} --> ${toId}`);
  }

  // 加入圖例
  if (functions.some(f => f.kind === 'method')) {
    lines.push('');
    lines.push('    %% Legend: [] = function, {} = method');
  }

  if (callRelations.length === 0) {
    notes.push('no_call_relations_found');
  }

  return { code: lines.join('\n'), notes };
}

/**
 * 生成序列圖（基礎版本）
 */
function generateSequenceDiagram(ir, options = {}) {
  const lines = ['sequenceDiagram'];
  const notes = [];

  // 獲取所有類別作為參與者
  const classes = ir.entities.filter(e => e.kind === 'class');
  
  // 聲明參與者
  for (const cls of classes) {
    lines.push(`    participant ${sanitizeName(cls.name)}`);
  }

  // 基於方法呼叫生成訊息
  const callRelations = ir.relations.filter(r => r.type === 'CALLS');
  
  for (const rel of callRelations) {
    const fromEntity = findEntity(ir, rel.from);
    const toEntity = findEntity(ir, rel.to);
    
    if (fromEntity && toEntity) {
      const fromClass = getEntityClass(ir, fromEntity);
      const toClass = getEntityClass(ir, toEntity);
      
      if (fromClass && toClass && fromClass !== toClass) {
        lines.push(`    ${sanitizeName(fromClass)} ->> ${sanitizeName(toClass)}: ${toEntity.name}()`);
      }
    }
  }

  if (classes.length === 0) {
    notes.push('no_participants_found');
  }

  return { code: lines.join('\n'), notes };
}

/**
 * 輔助函數
 */
function getClassProperties(ir, classEntity) {
  // 暫時返回空陣列，後續可擴展屬性分析
  return [];
}

function getClassMethods(ir, classEntity) {
  return ir.entities.filter(e => 
    e.kind === 'method' && 
    e.data?.class === classEntity.name
  );
}

function getRelationSymbol(relationType) {
  const symbols = {
    'EXTENDS': '<|--',
    'IMPLEMENTS': '<|..',
    'USES': '<--',
    'DEPENDS_ON': '<..'
  };
  return symbols[relationType] || '-->';
}

function getEntityClass(ir, entity) {
  if (entity.kind === 'method' && entity.data?.class) {
    return entity.data.class;
  }
  if (entity.kind === 'class') {
    return entity.name;
  }
  return null;
}

function sanitizeName(name) {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

function sanitizeId(id) {
  return id.replace(/[^a-zA-Z0-9_]/g, '_');
}

// 匯出所有生成器
export {
  generateClassDiagram,
  generateFlowchart,
  generateDependencyGraph,
  generateCallGraph,
  generateSequenceDiagram
};